### ISSUE TITLE
 'RoutingModel' object has no attribute 'SetPickupAndDeliveryPolicyOfAllVehicles'

### ISSUE THREAD

**Issue by tk120404** [google/or-tools#1137]
Traceback (most recent call last):
  File "vrp_pickup_delivery_fifo.py", line 218, in <module>
    main()
  File "vrp_pickup_delivery_fifo.py", line 194, in main
    routing.SetPickupAndDeliveryPolicyOfAllVehicles(
  File "/Users/vansinsta/.local/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py", line 3182, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, RoutingModel, name)
  File "/Users/vansinsta/.local/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
**AttributeError: 'RoutingModel' object has no attribute 'SetPickupAndDeliveryPolicyOfAllVehicles'**

**Comment by Mizux** [comment]
You must use the master branch, where did you get this sample ?

**Comment by tk120404** [comment]
I got this in master branch.

**Comment by tk120404** [comment]
I have installed or tools thru pip install --user ortools==7.0b6150

**Comment by Mizux** [comment]
ok, master is ahead of this beta release, and leak has been fixed -> closing
