### ISSUE TITLE
Building Or-Tools from Source for .NET fails (7.1.6720).

### ISSUE THREAD

**Issue by ConnerWestover** [google/or-tools#1287]
I downloaded the source .zip file for 7.1 from https://developers.google.com/optimization/install/dotnet/source_windows and upon following the steps the solution I get fails to build in the `tools\make test_dotnet`. 

I've made no edits to the source code and I ran `tools\make clean_dotnet` prior to building. is there something I'm missing? 

Furthermore I tried forcing the package's DLLs to target an x64 framework, but this did not resolve the issue.

Error when running `tools\make test_dotnet`:
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_constraint_solver(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.new_Solver__SWIG_0(String jarg1)
   at Google.OrTools.ConstraintSolver.Solver..ctor(String name)
   at SimpleCpProgram.Main(String[] args) in C:\Users\cwestover\Desktop\or-tools-7.1\ortools\constraint_solver\samples\SimpleCpProgram.cs:line 33

**Comment by lperron** [comment]
are you using the command line tool from visual studio for x64 ?

**Comment by ConnerWestover** [comment]
I hadn't realized that the Developer Console for Visual Studio 2017 needed to be built for x64. Just followed the same steps as above and it successfully built and ran all of the tests. Thanks for the help!
