### ISSUE TITLE
segfault (core dump) or 0 cost solution, in  VRPPD,  and VRPPD with soft TW

### ISSUE THREAD

**Issue by yuyangch** [google/or-tools#1506]
Hi!
I am trying to formulate a VRPPD with soft TW, with code adopted from or-tool's 
VRPPD guide 
https://developers.google.com/optimization/routing/pickup_delivery
and VRPTW guide. 
https://developers.google.com/optimization/routing/vrptw

My intended minimization is the sum of each P or D 's wait time, assume all PD are given at time 0 (so i set soft time window [0,0] with 1 as penality coefficient)

The code attached below works with default sets of PD in guide. But if i added [9,3], it gives segfault error (gdb result attached)

Further, if i add both [9,3], [3,5] it returns a 0 cost, (empty?)solution  

Please point out my mistakes. Thank you in advance!

```python
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp
APPOINTMENT_PENALTY_COEFFICIENT=1
def create_data_model():
  """Stores the data for the problem."""
  data = {}
  data['time_matrix'] = [
      [0, 6, 9, 8, 7, 3, 6, 2, 3, 2, 6, 6, 4, 4, 5, 9, 7],
      [6, 0, 8, 3, 2, 6, 8, 4, 8, 8, 13, 7, 5, 8, 12, 10, 14],
      [9, 8, 0, 11, 10, 6, 3, 9, 5, 8, 4, 15, 14, 13, 9, 18, 9],
      [8, 3, 11, 0, 1, 7, 10, 6, 10, 10, 14, 6, 7, 9, 14, 6, 16],
      [7, 2, 10, 1, 0, 6, 9, 4, 8, 9, 13, 4, 6, 8, 12, 8, 14],
      [3, 6, 6, 7, 6, 0, 2, 3, 2, 2, 7, 9, 7, 7, 6, 12, 8],
      [6, 8, 3, 10, 9, 2, 0, 6, 2, 5, 4, 12, 10, 10, 6, 15, 5],
      [2, 4, 9, 6, 4, 3, 6, 0, 4, 4, 8, 5, 4, 3, 7, 8, 10],
      [3, 8, 5, 10, 8, 2, 2, 4, 0, 3, 4, 9, 8, 7, 3, 13, 6],
      [2, 8, 8, 10, 9, 2, 5, 4, 3, 0, 4, 6, 5, 4, 3, 9, 5],
      [6, 13, 4, 14, 13, 7, 4, 8, 4, 4, 0, 10, 9, 8, 4, 13, 4],
      [6, 7, 15, 6, 4, 9, 12, 5, 9, 6, 10, 0, 1, 3, 7, 3, 10],
      [4, 5, 14, 7, 6, 7, 10, 4, 8, 5, 9, 1, 0, 2, 6, 4, 8],
      [4, 8, 13, 9, 8, 7, 10, 3, 7, 4, 8, 3, 2, 0, 4, 5, 6],
      [5, 12, 9, 14, 12, 6, 6, 7, 3, 3, 4, 7, 6, 4, 0, 9, 2],
      [9, 10, 18, 6, 8, 12, 15, 8, 13, 9, 13, 3, 4, 5, 9, 0, 9],
      [7, 14, 9, 16, 14, 8, 5, 10, 6, 5, 4, 10, 8, 6, 2, 9, 0],
  ]
  data['pickups_deliveries'] = [
      [1, 6],
      [2, 10],
      [4, 3],
      [5, 9],
      [7, 8],
      [15, 11],
      [13, 12],
      [16, 14],
      [8, 1],
      #[9, 3],
      #[3,5],
  ]
  data['num_vehicles'] = 4
  data['depot'] = 0
  return data

def print_solution(data, manager, routing, assignment):
    """Prints assignment on console."""
    time_dimension = routing.GetDimensionOrDie('Time')
    total_time = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        while not routing.IsEnd(index):
            time_var = time_dimension.CumulVar(index)
            plan_output += '{0} Time({1},{2}) -> '.format(
                manager.IndexToNode(index), assignment.Min(time_var),
                assignment.Max(time_var))
            index = assignment.Value(routing.NextVar(index))
        time_var = time_dimension.CumulVar(index)
        plan_output += '{0} Time({1},{2})\n'.format(
            manager.IndexToNode(index), assignment.Min(time_var),
            assignment.Max(time_var))
        plan_output += 'Time of the route: {}min\n'.format(
            assignment.Min(time_var))
        print(plan_output)
        total_time += assignment.Min(time_var)
    print('Total time of all routes: {}min'.format(total_time))

def main():
    """Solve the VRP with time windows."""
    data = create_data_model()
    manager = pywrapcp.RoutingIndexManager(
        len(data['time_matrix']), data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    def time_callback(from_index, to_index):
        """Returns the travel time between the two nodes."""
        # Convert from routing variable Index to time matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return int(data['time_matrix'][from_node][to_node])
        #return int(data['time_matrix'][from_index][to_index])
    transit_callback_index = routing.RegisterTransitCallback(time_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
    time = 'Time'
    routing.AddDimension(
        transit_callback_index,
        10000,  # allow waiting time
        10000,  # maximum time per vehicle
        False,  # Don't force start cumul to zero.
        time)
    time_dimension = routing.GetDimensionOrDie(time)
    for request in data['pickups_deliveries']:
        pickup_index = manager.NodeToIndex(request[0])
        time_dimension.SetCumulVarSoftLowerBound(pickup_index, 0, APPOINTMENT_PENALTY_COEFFICIENT);
        time_dimension.SetCumulVarSoftUpperBound(pickup_index, 0, APPOINTMENT_PENALTY_COEFFICIENT);
        delivery_index = manager.NodeToIndex(request[1])
        time_dimension.SetCumulVarSoftLowerBound(delivery_index, 0, APPOINTMENT_PENALTY_COEFFICIENT);
        time_dimension.SetCumulVarSoftUpperBound(delivery_index, 0, APPOINTMENT_PENALTY_COEFFICIENT);
        routing.AddPickupAndDelivery(pickup_index, delivery_index)
        routing.solver().Add(
            routing.VehicleVar(pickup_index) == routing.VehicleVar(
                delivery_index))
        routing.solver().Add(
            time_dimension.CumulVar(pickup_index) <=
            time_dimension.CumulVar(delivery_index))
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.log_search = True
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION)
    assignment = routing.SolveWithParameters(search_parameters)
    if assignment:
        print_solution(data, manager, routing, assignment)

if __name__ == '__main__':
  main()
```
```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...Reading symbols from /usr/lib/debug/.build-id/dd/6fd4f087561148594326363d9e5c8ca3025c4e.debug...done.
done.
(gdb) run ORTOOLTIME.oy
Starting program: /usr/bin/python3 ORTOOLTIME.oy
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/usr/bin/python3: can't open file 'ORTOOLTIME.oy': [Errno 2] No such file or directory
[Inferior 1 (process 11307) exited with code 02]
(gdb) run ORTOOLTIME.py
Starting program: /usr/bin/python3 ORTOOLTIME.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0820 15:36:23.034255 11312 search.cc:254] Start search (memory used = 32.92 MB)
I0820 15:36:23.034358 11312 search.cc:254] Root node processed (time = 0 ms, constraints = 179, memory used = 32.92 MB)
I0820 15:36:23.037644 11312 search.cc:254] Solution #0 (604, time = 3 ms, branches = 58, failures = 1, depth = 33, memory used = 33.01 MB)
I0820 15:36:23.054172 11312 search.cc:254] Solution #1 (597, objective maximum = 604, time = 19 ms, branches = 85, failures = 3, depth = 33, PairRelocateOperator, neighbors = 245, filtered neighbors = 1, accepted neighbors = 1, memory used = 33.05 MB)
I0820 15:36:23.055991 11312 search.cc:254] Solution #2 (596, objective maximum = 604, time = 21 ms, branches = 96, failures = 5, depth = 33, PairRelocateOperator, neighbors = 300, filtered neighbors = 2, accepted neighbors = 2, memory used = 33.05 MB)
I0820 15:36:23.099261 11312 search.cc:254] Solution #3 (581, objective maximum = 604, time = 64 ms, branches = 123, failures = 7, depth = 33, PairRelocateOperator, neighbors = 1531, filtered neighbors = 3, accepted neighbors = 3, memory used = 33.05 MB)
I0820 15:36:23.142670 11312 search.cc:254] Solution #4 (559, objective maximum = 604, time = 108 ms, branches = 152, failures = 9, depth = 33, PairRelocateOperator, neighbors = 2753, filtered neighbors = 4, accepted neighbors = 4, memory used = 33.05 MB)
I0820 15:36:23.159850 11312 search.cc:254] Solution #5 (558, objective maximum = 604, time = 125 ms, branches = 162, failures = 11, depth = 33, PairRelocateOperator, neighbors = 3000, filtered neighbors = 5, accepted neighbors = 5, memory used = 33.05 MB)
I0820 15:36:23.161376 11312 search.cc:254] Solution #6 (549, objective maximum = 604, time = 126 ms, branches = 190, failures = 13, depth = 33, PairRelocateOperator, neighbors = 3007, filtered neighbors = 6, accepted neighbors = 6, memory used = 33.05 MB)
I0820 15:36:23.164229 11312 search.cc:254] Solution #7 (548, objective maximum = 604, time = 129 ms, branches = 200, failures = 15, depth = 33, PairRelocateOperator, neighbors = 3064, filtered neighbors = 7, accepted neighbors = 7, memory used = 33.05 MB)
I0820 15:36:23.213076 11312 search.cc:254] Solution #8 (541, objective maximum = 604, time = 178 ms, branches = 230, failures = 17, depth = 33, PairRelocateOperator, neighbors = 4285, filtered neighbors = 8, accepted neighbors = 8, memory used = 33.05 MB)
I0820 15:36:23.268302 11312 search.cc:254] Solution #9 (461, objective maximum = 604, time = 233 ms, branches = 257, failures = 19, depth = 33, PairRelocateOperator, neighbors = 5550, filtered neighbors = 9, accepted neighbors = 9, memory used = 33.05 MB)
I0820 15:36:23.272788 11312 search.cc:254] Solution #10 (446, objective maximum = 604, time = 238 ms, branches = 285, failures = 21, depth = 33, PairRelocateOperator, neighbors = 5614, filtered neighbors = 10, accepted neighbors = 10, memory used = 33.05 MB)
I0820 15:36:23.273391 11312 search.cc:254] Solution #11 (420, objective maximum = 604, time = 239 ms, branches = 312, failures = 23, depth = 33, PairRelocateOperator, neighbors = 5615, filtered neighbors = 11, accepted neighbors = 11, memory used = 33.05 MB)
I0820 15:36:23.273874 11312 search.cc:254] Solution #12 (418, objective maximum = 604, time = 239 ms, branches = 341, failures = 25, depth = 33, PairRelocateOperator, neighbors = 5616, filtered neighbors = 12, accepted neighbors = 12, memory used = 33.05 MB)
I0820 15:36:23.280336 11312 search.cc:254] Solution #13 (417, objective maximum = 604, time = 246 ms, branches = 350, failures = 27, depth = 33, PairRelocateOperator, neighbors = 5821, filtered neighbors = 13, accepted neighbors = 13, memory used = 33.05 MB)
I0820 15:36:23.280884 11312 search.cc:254] Solution #14 (415, objective maximum = 604, time = 246 ms, branches = 378, failures = 29, depth = 33, PairRelocateOperator, neighbors = 5822, filtered neighbors = 14, accepted neighbors = 14, memory used = 33.05 MB)
I0820 15:36:23.317298 11312 search.cc:254] Solution #15 (363, objective maximum = 604, time = 282 ms, branches = 405, failures = 31, depth = 33, PairRelocateOperator, neighbors = 6707, filtered neighbors = 15, accepted neighbors = 15, memory used = 33.08 MB)
I0820 15:36:23.318342 11312 search.cc:254] Solution #16 (350, objective maximum = 604, time = 284 ms, branches = 436, failures = 33, depth = 33, PairRelocateOperator, neighbors = 6720, filtered neighbors = 16, accepted neighbors = 16, memory used = 33.08 MB)
I0820 15:36:23.338210 11312 search.cc:254] Solution #17 (312, objective maximum = 604, time = 303 ms, branches = 463, failures = 35, depth = 33, PairRelocateOperator, neighbors = 7304, filtered neighbors = 17, accepted neighbors = 17, memory used = 33.08 MB)
I0820 15:36:23.348002 11312 search.cc:254] Solution #18 (308, objective maximum = 604, time = 313 ms, branches = 491, failures = 37, depth = 33, PairRelocateOperator, neighbors = 7532, filtered neighbors = 18, accepted neighbors = 18, memory used = 33.08 MB)
I0820 15:36:23.358705 11312 search.cc:254] Solution #19 (283, objective maximum = 604, time = 324 ms, branches = 518, failures = 39, depth = 33, PairRelocateOperator, neighbors = 8010, filtered neighbors = 19, accepted neighbors = 19, memory used = 33.08 MB)
I0820 15:36:23.359699 11312 search.cc:254] Solution #20 (272, objective maximum = 604, time = 325 ms, branches = 547, failures = 41, depth = 33, PairRelocateOperator, neighbors = 8023, filtered neighbors = 20, accepted neighbors = 20, memory used = 33.08 MB)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1162403 in operations_research::ExchangeSubtrip::ExtractChainsAndCheckCanonical(long, std::vector<long, std::allocator<long> >*, std::vector<long, std::allocator<long> >*) ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
(gdb) 
```
```
genji@Alienware-m15-laptop1:~$ uname -a
Linux Alienware-m15-laptop1 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:10:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yuyangch** [comment]
It seems the error is not limited to the above VRPPD with soft TW example,
An identical copy to the example of VRPPD guide, with only difference being 
1)relax vehicle max distance and slack, 
2)added PD [8,1] [9,3]

also produce segfault. Code and gdb output attached. 
OS info same as above

```python
from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp


def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['distance_matrix'] = [
        [
            0, 548, 776, 696, 582, 274, 502, 194, 308, 194, 536, 502, 388, 354,
            468, 776, 662
        ],
        [
            548, 0, 684, 308, 194, 502, 730, 354, 696, 742, 1084, 594, 480, 674,
            1016, 868, 1210
        ],
        [
            776, 684, 0, 992, 878, 502, 274, 810, 468, 742, 400, 1278, 1164,
            1130, 788, 1552, 754
        ],
        [
            696, 308, 992, 0, 114, 650, 878, 502, 844, 890, 1232, 514, 628, 822,
            1164, 560, 1358
        ],
        [
            582, 194, 878, 114, 0, 536, 764, 388, 730, 776, 1118, 400, 514, 708,
            1050, 674, 1244
        ],
        [
            274, 502, 502, 650, 536, 0, 228, 308, 194, 240, 582, 776, 662, 628,
            514, 1050, 708
        ],
        [
            502, 730, 274, 878, 764, 228, 0, 536, 194, 468, 354, 1004, 890, 856,
            514, 1278, 480
        ],
        [
            194, 354, 810, 502, 388, 308, 536, 0, 342, 388, 730, 468, 354, 320,
            662, 742, 856
        ],
        [
            308, 696, 468, 844, 730, 194, 194, 342, 0, 274, 388, 810, 696, 662,
            320, 1084, 514
        ],
        [
            194, 742, 742, 890, 776, 240, 468, 388, 274, 0, 342, 536, 422, 388,
            274, 810, 468
        ],
        [
            536, 1084, 400, 1232, 1118, 582, 354, 730, 388, 342, 0, 878, 764,
            730, 388, 1152, 354
        ],
        [
            502, 594, 1278, 514, 400, 776, 1004, 468, 810, 536, 878, 0, 114,
            308, 650, 274, 844
        ],
        [
            388, 480, 1164, 628, 514, 662, 890, 354, 696, 422, 764, 114, 0, 194,
            536, 388, 730
        ],
        [
            354, 674, 1130, 822, 708, 628, 856, 320, 662, 388, 730, 308, 194, 0,
            342, 422, 536
        ],
        [
            468, 1016, 788, 1164, 1050, 514, 514, 662, 320, 274, 388, 650, 536,
            342, 0, 764, 194
        ],
        [
            776, 868, 1552, 560, 674, 1050, 1278, 742, 1084, 810, 1152, 274,
            388, 422, 764, 0, 798
        ],
        [
            662, 1210, 754, 1358, 1244, 708, 480, 856, 514, 468, 354, 844, 730,
            536, 194, 798, 0
        ],
    ]
    data['pickups_deliveries'] = [
        [1, 6],
        [2, 10],
        [4, 3],
        [5, 9],
        [7, 8],
        [15, 11],
        [13, 12],
        [16, 14],
	[8,1],
	[9,3],
    ]
    data['num_vehicles'] = 10
    data['depot'] = 0
    return data


def print_solution(data, manager, routing, assignment):
    """Prints assignment on console."""
    total_distance = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        route_distance = 0
        while not routing.IsEnd(index):
            plan_output += ' {} -> '.format(manager.IndexToNode(index))
            previous_index = index
            index = assignment.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(
                previous_index, index, vehicle_id)
        plan_output += '{}\n'.format(manager.IndexToNode(index))
        plan_output += 'Distance of the route: {}m\n'.format(route_distance)
        print(plan_output)
        total_distance += route_distance
    print('Total Distance of all routes: {}m'.format(total_distance))


def main():
    """Entry point of the program."""
    # Instantiate the data problem.
    data = create_data_model()

    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(
        len(data['distance_matrix']), data['num_vehicles'], data['depot'])

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)


    # Define cost of each arc.
    def distance_callback(from_index, to_index):
        """Returns the manhattan distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['distance_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Add Distance constraint.
    dimension_name = 'Distance'
    routing.AddDimension(
        transit_callback_index,
        300000000,  # no slack
        300000000,  # vehicle maximum travel distance
        True,  # start cumul to zero
        dimension_name)
    distance_dimension = routing.GetDimensionOrDie(dimension_name)
    distance_dimension.SetGlobalSpanCostCoefficient(100)

    # Define Transportation Requests.
    for request in data['pickups_deliveries']:
        pickup_index = manager.NodeToIndex(request[0])
        delivery_index = manager.NodeToIndex(request[1])
        routing.AddPickupAndDelivery(pickup_index, delivery_index)
        routing.solver().Add(
            routing.VehicleVar(pickup_index) == routing.VehicleVar(
                delivery_index))
        routing.solver().Add(
            distance_dimension.CumulVar(pickup_index) <=
            distance_dimension.CumulVar(delivery_index))

    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
	
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION)

    # Solve the problem.
    search_parameters.log_search=True
    #search_parameters.time_limit.seconds=60000000
    assignment = routing.SolveWithParameters(search_parameters)

    # Print solution on console.
    if assignment:
        print_solution(data, manager, routing, assignment)


if __name__ == '__main__':
    main()

```
```
yuyangch@Alienware-m15-laptop1:~$gdb python3
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...Reading symbols from /usr/lib/debug/.build-id/dd/6fd4f087561148594326363d9e5c8ca3025c4e.debug...done.
done.
(gdb) run ORTOOLPD.py
Starting program: /usr/bin/python3 ORTOOLPD.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0822 13:05:23.759788 31830 search.cc:254] Start search (memory used = 32.94 MB)
I0822 13:05:23.759896 31830 search.cc:254] Root node processed (time = 0 ms, constraints = 246, memory used = 32.94 MB)
I0822 13:05:23.763028 31830 search.cc:254] Solution #0 (650036, time = 3 ms, branches = 47, failures = 1, depth = 33, memory used = 32.97 MB)
I0822 13:05:23.767805 31830 search.cc:254] Solution #1 (633876, objective maximum = 650036, time = 7 ms, branches = 63, failures = 3, depth = 33, PairRelocateOperator, neighbors = 299, filtered neighbors = 1, accepted neighbors = 1, memory used = 32.97 MB)
I0822 13:05:23.780181 31830 search.cc:254] Solution #2 (573212, objective maximum = 650036, time = 20 ms, branches = 81, failures = 5, depth = 33, PairRelocateOperator, neighbors = 1566, filtered neighbors = 2, accepted neighbors = 2, memory used = 32.97 MB)
I0822 13:05:23.780934 31830 search.cc:254] Solution #3 (566344, objective maximum = 650036, time = 21 ms, branches = 98, failures = 7, depth = 33, PairRelocateOperator, neighbors = 1577, filtered neighbors = 3, accepted neighbors = 3, memory used = 32.97 MB)
I0822 13:05:23.782613 31830 search.cc:254] Solution #4 (563920, objective maximum = 650036, time = 22 ms, branches = 117, failures = 9, depth = 33, PairRelocateOperator, neighbors = 1660, filtered neighbors = 4, accepted neighbors = 4, memory used = 32.97 MB)
I0822 13:05:23.783807 31830 search.cc:254] Solution #5 (550184, objective maximum = 650036, time = 23 ms, branches = 134, failures = 11, depth = 33, PairRelocateOperator, neighbors = 1857, filtered neighbors = 5, accepted neighbors = 5, memory used = 32.97 MB)
I0822 13:05:23.784986 31830 search.cc:254] Solution #6 (547760, objective maximum = 650036, time = 25 ms, branches = 152, failures = 13, depth = 33, PairRelocateOperator, neighbors = 1977, filtered neighbors = 6, accepted neighbors = 6, memory used = 32.97 MB)
I0822 13:05:23.786438 31830 search.cc:254] Solution #7 (534024, objective maximum = 650036, time = 26 ms, branches = 169, failures = 15, depth = 33, PairRelocateOperator, neighbors = 2193, filtered neighbors = 7, accepted neighbors = 7, memory used = 32.97 MB)
I0822 13:05:23.795047 31830 search.cc:254] Solution #8 (489520, objective maximum = 650036, time = 35 ms, branches = 190, failures = 17, depth = 33, PairRelocateOperator, neighbors = 3081, filtered neighbors = 8, accepted neighbors = 8, memory used = 32.97 MB)
I0822 13:05:23.799715 31830 search.cc:254] Solution #9 (441908, objective maximum = 650036, time = 39 ms, branches = 208, failures = 19, depth = 33, PairRelocateOperator, neighbors = 3716, filtered neighbors = 9, accepted neighbors = 9, memory used = 32.97 MB)
I0822 13:05:23.800242 31830 search.cc:254] Solution #10 (441680, objective maximum = 650036, time = 40 ms, branches = 227, failures = 21, depth = 33, PairRelocateOperator, neighbors = 3718, filtered neighbors = 10, accepted neighbors = 10, memory used = 32.97 MB)
I0822 13:05:23.800832 31830 search.cc:254] Solution #11 (441200, objective maximum = 650036, time = 41 ms, branches = 245, failures = 23, depth = 33, PairRelocateOperator, neighbors = 3728, filtered neighbors = 11, accepted neighbors = 11, memory used = 32.97 MB)
I0822 13:05:23.803933 31830 search.cc:254] Solution #12 (428216, objective maximum = 650036, time = 44 ms, branches = 265, failures = 25, depth = 33, PairRelocateOperator, neighbors = 4257, filtered neighbors = 12, accepted neighbors = 12, memory used = 32.97 MB)
I0822 13:05:23.804478 31830 search.cc:254] Solution #13 (421348, objective maximum = 650036, time = 44 ms, branches = 283, failures = 27, depth = 33, PairRelocateOperator, neighbors = 4261, filtered neighbors = 13, accepted neighbors = 13, memory used = 32.97 MB)
I0822 13:05:23.805050 31830 search.cc:254] Solution #14 (409588, objective maximum = 650036, time = 45 ms, branches = 303, failures = 29, depth = 33, PairRelocateOperator, neighbors = 4268, filtered neighbors = 14, accepted neighbors = 14, memory used = 32.97 MB)
I0822 13:05:23.805768 31830 search.cc:254] Solution #15 (409564, objective maximum = 650036, time = 45 ms, branches = 319, failures = 31, depth = 33, PairRelocateOperator, neighbors = 4290, filtered neighbors = 15, accepted neighbors = 15, memory used = 32.97 MB)
I0822 13:05:23.806596 31830 search.cc:254] Solution #16 (409360, objective maximum = 650036, time = 46 ms, branches = 342, failures = 33, depth = 33, PairRelocateOperator, neighbors = 4320, filtered neighbors = 16, accepted neighbors = 16, memory used = 32.97 MB)
I0822 13:05:23.807302 31830 search.cc:254] Solution #17 (408880, objective maximum = 650036, time = 47 ms, branches = 361, failures = 35, depth = 33, PairRelocateOperator, neighbors = 4334, filtered neighbors = 17, accepted neighbors = 17, memory used = 32.97 MB)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1195403 in operations_research::ExchangeSubtrip::ExtractChainsAndCheckCanonical(long, std::vector<long, std::allocator<long> >*, std::vector<long, std::allocator<long> >*) ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
(gdb) bt
#0  0x00007ffff1195403 in operations_research::ExchangeSubtrip::ExtractChainsAndCheckCanonical(long, std::vector<long, std::allocator<long> >*, std::vector<long, std::allocator<long> >*) ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#1  0x00007ffff1195538 in operations_research::ExchangeSubtrip::MakeNeighbor() ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#2  0x00007ffff10de1a8 in operations_research::PathOperator::MakeOneNeighbor() ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#3  0x00007ffff10dcc00 in operations_research::IntVarLocalSearchOperator::MakeNextNeighbor(operations_research::Assignment*, operations_research::Assignment*) () from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#4  0x00007ffff10dbede in operations_research::(anonymous namespace)::CompoundOperator::MakeNextNeighbor(operations_research::Assignment*, operations_research::Assignment*) ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#5  0x00007ffff10e677c in operations_research::FindOneNeighbor::Next(operations_research::Solver*) ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#6  0x00007ffff103593d in operations_research::Solver::NextSolution() ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#7  0x00007ffff1036b6f in operations_research::Solver::SolveAndCommit(operations_research::DecisionBuilder*, std::vector<operations_research::SearchMonitor*, std::allocator<operations_research::SearchMonitor*> > const&) ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#8  0x00007ffff10dbd0d in operations_research::(anonymous namespace)::NestedSolveDecision::Apply(operations_research::Solver*) ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#9  0x00007ffff1035a49 in operations_research::Solver::NextSolution() ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#10 0x00007ffff1036438 in operations_research::Solver::Solve(operations_research::DecisionBuilder*, std::vector<operations_research::SearchMonitor*, std::allocator<operations_research::SearchMonitor*> > const&) ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#11 0x00007ffff115c362 in operations_research::RoutingModel::SolveFromAssignmentWithParameters(operations_research::Assignment const*, operations_research::RoutingSearchParameters const&, std::vector<operations_research::Assignment const*, std::allocator<operations_research::Assignment const*> >*) () from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/../.libs/libortools.so
#12 0x00007ffff3de8550 in _wrap_RoutingModel_SolveWithParameters ()
   from /home/yuyangch/.local/lib/python3.5/site-packages/ortools/constraint_solver/_pywrapcp.so
#13 0x00000000004ea10f in PyCFunction_Call () at ../Objects/methodobject.c:109
#14 0x0000000000536d94 in call_function (oparg=<optimized out>, pp_stack=0x7fffffffd580) at ../Python/ceval.c:4705
#15 PyEval_EvalFrameEx () at ../Python/ceval.c:3236
#16 0x000000000053fc97 in _PyEval_EvalCodeWithName () at ../Python/ceval.c:4018
#17 0x000000000053b83f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffffd790, 
    func=<optimized out>) at ../Python/ceval.c:4813
#18 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd790) at ../Python/ceval.c:4730
---Type <return> to continue, or q <return> to quit---
#19 PyEval_EvalFrameEx () at ../Python/ceval.c:3236
#20 0x00000000005401ef in _PyEval_EvalCodeWithName () at ../Python/ceval.c:4018
#21 0x000000000053bc93 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffffd9a0, 
    func=<optimized out>) at ../Python/ceval.c:4813
#22 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd9a0) at ../Python/ceval.c:4730
#23 PyEval_EvalFrameEx () at ../Python/ceval.c:3236
#24 0x000000000053fc97 in _PyEval_EvalCodeWithName () at ../Python/ceval.c:4018
#25 0x00000000005409bf in PyEval_EvalCodeEx () at ../Python/ceval.c:4039
#26 PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at ../Python/ceval.c:777
#27 0x000000000060cb42 in run_mod () at ../Python/pythonrun.c:976
#28 0x000000000060efea in PyRun_FileExFlags () at ../Python/pythonrun.c:929
#29 0x000000000060f7dc in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:396
#30 0x0000000000640256 in run_file (p_cf=0x7fffffffdc10, filename=0xa75200 L"ORTOOLPD.py", fp=0xb377b0) at ../Modules/main.c:318
#31 Py_Main () at ../Modules/main.c:768
#32 0x00000000004d0001 in main () at ../Programs/python.c:65
#33 0x00007ffff7810830 in __libc_start_main (main=0x4cff20 <main>, argc=2, argv=0x7fffffffde28, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde18) at ../csu/libc-start.c:291
#34 0x00000000005d6999 in _start ()
(gdb) 



```

**Comment by yuyangch** [comment]
Sorry, I should have added 
or-tool version: 7.3.7083
python3 version 3.5.2
platform architecture: 64bit
python3 -m pip --version  : 19.1.1

**Comment by yuyangch** [comment]
After reading previous issues, i found the problem

-"the solver cannot visit the same node twice. You need to make dummy nodes for the repeated nodes. "
