### ISSUE TITLE
power of variable for linear integer

### ISSUE THREAD

**Issue by forkjoseph** [google/or-tools#1615]
Hi, 

I'm a bit newbie here. I'm trying to use OR tools to solve 4 + x + x^2 + y, extending example from https://developers.google.com/optimization/mip/integer_opt. 

When I pass `solver.Maximize(4 + x + x*x + y)`, it throws error like:

```
Original exception was:
Traceback (most recent call last):
  File "check.py", line 52, in <module>
    main()
  File "check.py", line 29, in main
    solver.Maximize(4 + x + x*x +y)
  File "/home/josephlee/.local/lib/python3.6/site-packages/ortools/linear_solver/pywraplp.py", line 611, in <lambda>
    lambda self, *args: getattr(VariableExpr(self), opname)(*args))
  File "/home/josephlee/.local/lib/python3.6/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 117, in __mul__
    return ProductCst(self, cst)
  File "/home/josephlee/.local/lib/python3.6/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 179, in __init__
    raise TypeError
TypeError
```

Is there a way to use X power of N  (x^n) as an objective function to maximize?

**Comment by lperron** [comment]
We do not (yet) support quadratic objective for the linear solver.
You need to use the solver native API.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by forkjoseph** [comment]
could you give me a pointer to "solver native API"?

**Comment by lperron** [comment]
Look for at IP-Opt, Gurobi quadratic API, SCIP quadratic API.

I do not know, I do not support them.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
