### ISSUE TITLE
Create an OrTools + SCIP *.whl file for a Docker Container.

### ISSUE THREAD

**Issue by SpyRefused** [google/or-tools#1618]
Hi, I'm trying to create an installable or-tools package using as a third party solver SCIP.

The question is that I do manual compilation following the guide: https://developers.google.com/optimization/install/python/source_linux

Once I have the *.whl I include it inside a docker container that installs this package via PIP in the Build process (Dockerfile).

`RUN pip install /app/whl/ortools-7.4.7240-cp36-cp36m-linux_x86_64.whl`

Everything seems to be fine, but then, it doesn't find any SCIP references.

My question is: do I also need to have SCIP inside the container? It is not included in the package when creating the *.whl if I have followed the steps of compiling with a third party solver?

This is what I get when I run the "# python -c "from ortools.linear_solver import pywraplp" inside the container that has the *.whl installed: 

```
root@d9deea192a78:/app# python -c "from ortools.linear_solver import pywraplp"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ortools/linear_solver/pywraplp.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libscip.so.6.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ortools/linear_solver/pywraplp.py", line 17, in <module>
    _pywraplp = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/ortools/linear_solver/pywraplp.py", line 16, in swig_import_helper
    return importlib.import_module('_pywraplp')
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywraplp'
```
I'm sorry for the question, I may be very silly, but I haven't been able to make this point clear to me.

Thank you, greetings.

**Comment by lperron** [comment]
You need to patch everything in the archiving process to copy scip libraries:
  - you need to copy the scip libraries to temp_python36 subdir
  - you need to patch the setup.py to include these libraries in the relocation process
