### ISSUE TITLE
Publish: dependencies missing

### ISSUE THREAD

**Issue by starnutoditopo** [google/or-tools#1638]
In a project that makes use of OR tools, it looks like the publish task (dotnet publish) forgets some dependencies.
No error is reported during the publishing process, but, once deployed, the following exception occurs at runtime:

`System.TypeInitializationException: The type initializer for 'Google.OrTools.Algorithms.operations_research_algorithmsPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Google.OrTools.runtime.win-x64.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Google.OrTools.Algorithms.operations_research_algorithmsPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_algorithms(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.Algorithms.operations_research_algorithmsPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.Algorithms.operations_research_algorithmsPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.Algorithms.operations_research_algorithmsPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.Algorithms.operations_research_algorithmsPINVOKE.new_KnapsackSolver__SWIG_1(Int32 jarg1, String jarg2)
   at Google.OrTools.Algorithms.KnapsackSolver..ctor(SolverType solver_type, String solver_name)
...`

**Comment by lperron** [comment]
most likely you need to install visual studio 2017 redistributables.
This module has been installed by many people successfully.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 11 oct. 2019 à 11:53, Starnuto di topo <notifications@github.com> a
écrit :
