### ISSUE TITLE
make install_python_modules fails

### ISSUE THREAD

**Issue by swethmandava** [google/or-tools#175]
Followed installation instructions. After make third_party , make install_python_modules fails with the following error. Can't figure out what the issue is, any ideas?

cd dependencies/sources/protobuf-3.0.0-beta-2/python && python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from setuptools import setup, Extension, find_packages
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/usr/lib/python2.7/dist-packages/setuptools/extension.py", line 7, in <module>
    from setuptools.dist import _get_unpatched
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 16, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2760, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 738, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2760, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2314, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2305, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1369, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1361, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1470, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b2.post2-py2.7.egg/EGG-INFO/namespace_packages.txt'
make: *** [install_python_modules] Error 1

**Comment by lperron** [comment]
are you on debian?

**Comment by swethmandava** [comment]
No, I'm on Ubuntu

**Comment by lperron** [comment]
it seems the protobuf package was already installed , with root privileges.
Is that possible?

**Comment by swethmandava** [comment]
How do I install it locally? Sorry for the ignorance, fairly new to this

**Comment by swethmandava** [comment]
Got it! 
Used sudo make install_python_modules instead
