### ISSUE TITLE
ImportError: DLL load failed while importing _pywrapsat

### ISSUE THREAD

**Issue by fpnick** [google/or-tools#1874]
**What version of OR-tools and what language are you using?**
Version: 7.5.7466
Language: Python 3.8

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
1. from ortools.sat.python import cp_model

**What did you expect to see**
Expected to be able to use cp_model like I was in ortools version 7.2.6977

**What did you see instead?**
```
Traceback (most recent call last):
  File "einsatzplanung\main.py", line 8, in <module>
    import assign
  File "C:\Users\Fabian.Nick\Documents\...........\assign.py", line 13, in <module>
    from ortools.sat.python import cp_model
  File "C:\Users\Fabian.Nick\.conda\envs\Python 3 Newest Shit\lib\site-packages\ortools\sat\python\cp_model.py", line 59, in <module>
    from ortools.sat import pywrapsat
  File "C:\Users\Fabian.Nick\.conda\envs\Python 3 Newest Shit\lib\site-packages\ortools\sat\pywrapsat.py", line 13, in <module>
    from . import _pywrapsat
ImportError: DLL load failed while importing _pywrapsat: Das angegebene Modul wurde nicht gefunden.
```

Make sure you include information that can help us debug (full error message, model Proto).
This used to work with Python 3.7.3 and ortools 7.2.6977

**Comment by stradivari96** [comment]
May be related to: https://github.com/google/or-tools/issues/1872

> On windows when trying to use wrapped language aka Python, Java or .Net,
A user must have the Microsoft Visual C++ Redistributable for Visual Studio 2019 installed on its machine...
