### ISSUE TITLE
Can't run google or tools project from command line. 

### ISSUE THREAD

**Issue by danielkboyer** [google/or-tools#1875]
I am using the latest version of google or tools in nuget package manager, my target framework for all four projects is .NET 4.7.2

Using Routing Solver

Windows

I can run the solution and see the correct output when debugging locally inside of visual studio, however when I build (using x64) and try to run the exe, nothing appears or happens. I installed this as an application inside of the azure cloud and it runs but then fails with the message. 

_Unhandled Exception: System.TypeInitializationException: The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'google-ortools-native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_constraint_solver(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.new_RoutingIndexManager__SWIG_1(Int32 jarg1, Int32 jarg2, Int32 length3, Int32[] jarg3, Int32 length4, Int32[] jarg4)
   at Google.OrTools.ConstraintSolver.RoutingIndexManager..ctor(Int32 num_nodes, Int32 num_vehicles, Int32[] starts, Int32[] ends)
   at DatosRoutingModelCloud.<Main>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DatosRoutingModelCloud.<Main>(String[] args)
_

I have not changed a line of code between running it in visual studio and building it. I then zip the build and run it as an application on a vm

It seems this is similar to [this ](https://github.com/google/or-tools/issues/1862) however my problem isn't running it but rather packaging it for a VM

**Comment by lperron** [comment]
Have you installed visual studio 2019 redistributable libraries ?

Le mer. 12 févr. 2020 à 00:33, Daniel Boyer <notifications@github.com> a
écrit :

**Comment by danielkboyer** [comment]
@lperron Yes I Installed this yesterday.

Further investigation, I am building as a dll and running the command dotnet "path to dll" and it's saying I need a runtime configuration. I have also tried dotnet build, dotnet run, dotnet publish with no success.

**Comment by ptr1120** [comment]
You said, you are using Netframework  4.7.2 project. Why do you use netcore (`dotnet `command) for such type of project?

**Comment by danielkboyer** [comment]
At first I wasn't, I would build as a .exe. Package the output in release/x64/ and run that from command line. However this was giving me the error 

_
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'google-ortools-native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_constraint_solver(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.new_RoutingIndexManager__SWIG_1(Int32 jarg1, Int32 jarg2, Int32 length3, Int32[] jarg3, Int32 length4, Int32[] jarg4)
   at Google.OrTools.ConstraintSolver.RoutingIndexManager..ctor(Int32 num_nodes, Int32 num_vehicles, Int32[] starts, Int32[] ends)
   at DatosRoutingModelCloud.<Main>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DatosRoutingModelCloud.<Main>(String[] args)
_

So I was trying a different approach following [this ](https://github.com/google/or-tools/issues/1862)issue

**Comment by danielkboyer** [comment]
Got it!!
@ptr1120 was right do not use dotnet command as I am in a .net framework project not net core (I was going insane trying everything)

The solution was a bit more hidden. In a warning on the build console it said I must reference Microsoft.BCl.Build in order to reference one of my projects which must of had a dependency I needed for goole or tools. 
 Now I can build the .exe file and run it on my computer.

**Comment by gmenaka** [comment]
Dear Team, I have blazor app (dotnet core 3.1) app and I use Google.OrTools package.
<TargetFramework>netcoreapp3.1</TargetFramework>
..
  <PackageReference Include="Google.OrTools" Version="7.5.7466" />

I use using Google.OrTools.Sat; 
and CpSolver

My Local all fine and working properly.

I deployed the app to Azure web app and start all the issues. . I get following erro. Could you please help he, how to fix this?

System.TypeInitializationException: The type initializer for 'Google.OrTools.Util.operations_research_utilPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'google-ortools-native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Google.OrTools.Util.operations_research_utilPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_util(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.Util.operations_research_utilPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.Util.operations_research_utilPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.Util.operations_research_utilPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.Util.operations_research_utilPINVOKE.new_Domain__SWIG_2(Int64 jarg1, Int64 jarg2)
   at SMTeam.Services.Glop.GolpExtensions.PrepareVariables(CpModel model, IOrderedEnumerable`1 orderedTaskMatrix, Int32 horizon) in C:\Dev\SMTeam\SMTeam.Services\Glop\GolpExtensions.cs:line 63
   at SMTeam.Services.Glop.GolpExtensions.GetTaskSequenceSolution(List`1 tasksMatrix) in C:\Dev\SMTeam\SMTeam.Services\Glop\GolpExtensions.cs:line 23
   at SMTeam.Services.TaskService.GetJointSolution(TaskSequenceConfirmationViewModel model, List`1 tasks) in C:\Dev\SMTeam\SMTeam.Services\TaskService.cs:line 1396
   at SMTeam.Services.TaskService.GetTaskSequenceForConfirmationAsync(Int32 idProject, String loggedUser, EProjectStates projectState) in C:\Dev\SMTeam\SMTeam.Services\TaskService.cs:line 1325
   at SMTeam.Web.Pages.Tasks.TaskSequencesConfirmation.OnAfterRenderAsync(Boolean firstRender) in C:\Dev\SMTeam\SMTeam.Web\Pages\Tasks\TaskSequencesConfirmation.razor:line 127
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
2020-06-23 21:52:33.364 +02:00 [ERR] Unhandled exception in circuit '1wJlQNvKfMxO0xY9ER51IusNLnCWgqs7dvvJI92pj_E'.
System.TypeInitializationException: The type initializer for 'Google.OrTools.Util.operations_research_utilPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'google-ortools-native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Google.OrTools.Util.operations_research_utilPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_util(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.Util.operations_research_utilPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.Util.operations_research_utilPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.Util.operations_research_utilPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.Util.operations_research_utilPINVOKE.new_Domain__SWIG_2(Int64 jarg1, Int64 jarg2)
   at SMTeam.Services.Glop.GolpExtensions.PrepareVariables(CpModel model, IOrderedEnumerable`1 orderedTaskMatrix, Int32 horizon) in C:\Dev\SMTeam\SMTeam.Services\Glop\GolpExtensions.cs:line 63
   at SMTeam.Services.Glop.GolpExtensions.GetTaskSequenceSolution(List`1 tasksMatrix) in C:\Dev\SMTeam\SMTeam.Services\Glop\GolpExtensions.cs:line 23
   at SMTeam.Services.TaskService.GetJointSolution(TaskSequenceConfirmationViewModel model, List`1 tasks) in C:\Dev\SMTeam\SMTeam.Services\TaskService.cs:line 1396
   at SMTeam.Services.TaskService.GetTaskSequenceForConfirmationAsync(Int32 idProject, String loggedUser, EProjectStates projectState) in C:\Dev\SMTeam\SMTeam.Services\TaskService.cs:line 1325
   at SMTeam.Web.Pages.Tasks.TaskSequencesConfirmation.OnAfterRenderAsync(Boolean firstRender) in C:\Dev\SMTeam\SMTeam.Web\Pages\Tasks\TaskSequencesConfirmation.razor:line 127
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by Mizux** [comment]
You need to install the  "visual studio 2019 redistributable" libraries on your azure instance.
I don't know how to do it...
