### ISSUE TITLE
ERROR: OverflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64'

### ISSUE THREAD

**Issue by arunandroapps** [google/or-tools#1930]
I want route should be prepared from distance matrix it while generating distance matrix using
```python
#!/usr/bin/python
from __future__ import division
from __future__ import print_function
import requests
import json
import urllib.request


def create_data():
  """Creates the data."""
  data = {}
  data['API_key'] = 'API_KEY'
  data['addresses'] = ["Sector 11, CBD Belapur Navi Mumbai, Maharashtra 400614","Palava Lakeshore Greens, Usarghar Gaon, Thane, Maharashtra, India","Rajhans Co-operative Housing Society, Best Colony, Mankur, Mumbai, Maharashtra, India","Mangala Residency, Sector 24, Taloja Panchanand, Taloja, Navi Mumbai, Maharashtra, India","Sai Arcade Building, Shivaji Nagar, Kopargaon, Dombivli West, Dombivli, Maharashtra, India","Kaushalya Medical Foundation Trust Hospital, opp. Nitin Company, Ramabai Ambedkar Nagar, Ganeshwadi, Thane West, Thane, Maharashtra, India","Mumbra, Thane, Maharashtra, India","Today Pearl Co-Operative Housing Society, Sector 24, Kamothe, Panvel, Navi Mumbai, Maharashtra, India","twins hallmark, Sector 19A, Sector 20, Kopar Khairane, Navi Mumbai, Maharashtra, India","Sector 8, Kopar Khairane, Navi Mumbai, Maharashtra, India","Nerul Railway Station (W), Nerul East, Nerul West, Nerul, Navi Mumbai, Maharashtra","New Mhada Colony, Dr.Babsaheb Ambedker Nagar, Govandi East, Mumbai, Maharashtra 400043, India","Kolekar Hospital & ICCU, Chembur Gaothan, Chembur, Mumbai, Maharashtra, India","Sector 15, Kopar Khairane, Navi Mumbai, Maharashtra 400709, India","Shahabaz Village, Sector 20, CBD Belapur, Navi Mumbai, Maharashtra, India","Sector 5, CBD Belapur, Navi Mumbai, Maharashtra, India","Shree Dattamandir Naupada Village, Kamothe, Panvel, Navi Mumbai, Maharashtra 410206","Sector 10, Kamothe, Panvel, Navi Mumbai, Maharashtra, India","Prisha Apartment, Gothivali Village, Sector 30, Ghansoli, Navi Mumbai, Maharashtra, India","Diwale Koliwada Bus Stop, Sector 15, CBD Belapur, Navi Mumbai, Maharashtra, India","Gaondevi Mandir, Badlapur E, Anand Nagar, Gaodevi, Badlapur, Maharashtra, India","Koproli Bus Stand, Koproli, Maharashtra, India","Kopar Khairane, Navi Mumbai, Maharashtra, India"]
  return data

def create_distance_matrix(data):
  addresses = data["addresses"]
  API_key = data["API_key"]
  # Distance Matrix API only accepts 100 elements per request, so get rows in multiple requests.
  max_elements = 100
  num_addresses = len(addresses) # 16 in this example.
  # Maximum number of rows that can be computed per request (6 in this example).
  max_rows = max_elements // num_addresses
  # num_addresses = q * max_rows + r (q = 2 and r = 4 in this example).
  q, r = divmod(num_addresses, max_rows)
  
  dest_addresses = addresses
  distance_matrix = []
  # Send q requests, returning max_rows rows per request.
  for i in range(q):
    origin_addresses = addresses[i * max_rows: (i + 1) * max_rows]
    response = send_request(origin_addresses, dest_addresses, API_key)
    distance_matrix += build_distance_matrix(response)

  # Get the remaining remaining r rows, if necessary.
  if r > 0:
    origin_addresses = addresses[q * max_rows: q * max_rows + r]
    response = send_request(origin_addresses, dest_addresses, API_key)
    distance_matrix += build_distance_matrix(response)
  return distance_matrix

def send_request(origin_addresses, dest_addresses, API_key):
  # print(origin_addresses)
  # print("-")
  """ Build and send request for the given origin and destination addresses."""
  def build_address_str(addresses):
    # Build a pipe-separated string of addresses
    
    address_str = ''
    for i in range(len(addresses) - 1):
      address_str += addresses[i].replace(" ", "+") + '|'
    address_str += addresses[-1].replace(" ", "+")
    return address_str

  request = 'https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial'
  origin_address_str = build_address_str(origin_addresses)
  dest_address_str = build_address_str(dest_addresses)
  request = request + '&origins=' + origin_address_str + '&destinations=' + \
                       dest_address_str + '&key=' + API_key

  jsonResult = urllib.request.urlopen(request).read()
  
  response = json.loads(jsonResult.decode('utf-8'))
  # print(response)
  return response

def build_distance_matrix(response):
  distance_matrix = []
  for row in response['rows']:
    row_list = [row['elements'][j]['distance']['value'] for j in range(len(row['elements']))]
    distance_matrix.append(row_list)
  return distance_matrix

########
# Main #
########
def main():
  """Entry point of the program"""
  # Create the data.
  data = create_data()
  addresses = data['addresses']
  API_key = data['API_key']
  distance_matrix = create_distance_matrix(data)
  print(distance_matrix)
if __name__ == '__main__':
  main()


It Returns:-
[[0, 26327, 22476, 12925, 34489, 24847, 22444, 11012, 13281, 11750, 5841, 16724, 21450], [26675, 0, 33665, 14093, 14360, 25077, 13370, 21886, 17060, 17587, 26140, 31404, 37595], [22826, 33665, 0, 33317, 40518, 15036, 25652, 31404, 20544, 19885, 19413, 6572, 4853], [13098, 13900, 33303, 0, 27276, 27971, 16265, 8309, 19954, 20481, 17899, 27551, 32277], [34841, 14228, 40462, 27160, 0, 28678, 20167, 32700, 23857, 24384, 32937, 38201, 44392], [26941, 25466, 15047, 28355, 30234, 0, 11135, 35519, 17145, 16486, 25037, 20696, 18977], [22926, 13367, 25367, 16257, 20220, 10747, 0, 21797, 11942, 12469, 21023, 26287, 29297], [10420, 21145, 30625, 7744, 32235, 32996, 21223, 0, 21431, 19899, 15221, 24874, 29600], [13597, 17090, 19305, 19979, 23942, 14063, 11897, 22175, 0, 1648, 10265, 12560, 17286], [12926, 17658, 19829, 20548, 24510, 14587, 12466, 21504, 1666, 0, 9384, 11679, 16405], [6048, 24728, 18798, 17911, 31581, 21939, 19536, 15998, 10128, 9325, 0, 13046, 17772], [17655, 31224, 6177, 28146, 38076, 20374, 30989, 26233, 13029, 12227, 14242, 0, 5869], [21534, 35103, 4872, 32025, 41955, 19068, 29684, 30112, 16908, 16106, 18121, 6000, 0], [9870, 20626, 30076, 7225, 31716, 32447, 20704, 1335, 20881, 19350, 14672, 24324, 29050], [9091, 22095, 29297, 8693, 33185, 31668, 22173, 1535, 20102, 18571, 13893, 23545, 28271], [15805, 19130, 15014, 22020, 25983, 11755, 13938, 24383, 5191, 5350, 13901, 19165, 18944], [841, 27084, 23233, 13682, 35246, 25604, 23201, 11769, 14038, 12507, 5184, 17482, 22208], [43037, 17023, 48659, 29861, 25754, 40070, 28364, 37654, 32053, 32580, 41134, 46398, 52589], [22529, 45936, 43019, 32534, 55032, 45390, 42987, 25436, 34527, 33725, 24501, 37267, 41993], [12942, 17291, 19845, 20181, 24144, 14604, 12099, 21520, 632, 993, 9610, 11905, 16631]]
```

After that while passing this value to
```python
"""Vehicles Routing Problem (VRP)."""

from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp


def create_data_model():
    """Stores the data for the problem."""

    data = {}
    data['demands'] = DEMANDS
    data['vehicle_capacities'] = [4] * NUM_VEHICLES
    data['distance_matrix'] = DISTANCE_MATRIX
    data['num_vehicles'] = NUM_VEHICLES
    data['depot'] = 0
    return data


def print_solution(data, manager, routing, solution):
    """Prints solution on console."""
    result = []
    total_distance = 0
    total_load = 0
    for vehicle_id in range(data['num_vehicles']):
        # node_vehicle_id = manager.IndexToNode(vehicle_id)
        vehicle_id_node = {}
        # result.append([])
        vehicle_id_node['vehicle_id'] = vehicle_id
        vehicle_id_node['node'] = []

        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        route_distance = 0
        route_load = 0
        while not routing.IsEnd(index):
            node_index = manager.IndexToNode(index)
            route_load += data['demands'][node_index]
            plan_output += ' {0} Load({1}) -> '.format(node_index, route_load)

            vehicle_id_node['node'].append(node_index)

            previous_index = index
            index = solution.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(
                previous_index, index, vehicle_id)

        vehicle_id_node['node'].append(manager.IndexToNode(index))
        plan_output += ' {0} Load({1})\n'.format(manager.IndexToNode(index),
                                                 route_load)
        plan_output += 'Distance of the route: {}m\n'.format(route_distance)
        plan_output += 'Load of the route: {}\n'.format(route_load)
        # print(plan_output)
        total_distance += route_distance
        total_load += route_load

        result.append(vehicle_id_node)
    # print('Total distance of all routes: {}m'.format(total_distance))
    # print('Total load of all routes: {}'.format(total_load))
    print(result)




def main():
    """Solve the CVRP problem."""
    # Instantiate the data problem.
    data = create_data_model()

    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                           data['num_vehicles'], data['depot'])
    
    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)
    

    # Create and register a transit callback.
    def distance_callback(from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        
        return data['distance_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)
    # print(transit_callback_index)
    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Add Capacity constraint.
    def demand_callback(from_index):
        """Returns the demand of the node."""
        # Convert from routing variable Index to demands NodeIndex.
        from_node = manager.IndexToNode(from_index)
        return data['demands'][from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(
        demand_callback)

    dimension_name = 'Capacity'
    routing.AddDimensionWithVehicleCapacity(
        demand_callback_index,
        0,  # null capacity slack
        data['vehicle_capacities'],  # vehicle maximum capacities
        True,  # start cumul to zero
        dimension_name)
    
    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.AUTOMATIC)
    # print(search_parameters)
    # Solve the problem.
    
    solution = routing.SolveWithParameters(search_parameters)
    # print(solution)
    # Print solution on console.
    if solution:
        print_solution(data, manager, routing, solution)


if __name__ == '__main__':
    main()
```

It Returns Error:-
OverflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vrp-capacity-runable.py", line 125, in <module>
    main()
  File "vrp-capacity-runable.py", line 117, in main
    solution = routing.SolveWithParameters(search_parameters)
  File "/usr/local/lib/python3.5/dist-packages/ortools/constraint_solver/pywrapcp.py", line 3928, in SolveWithParameters
    return _pywrapcp.RoutingModel_SolveWithParameters(self, search_parameters, solutions)
SystemError: <built-in function RoutingModel_SolveWithParameters> returned a result with an error set

**What version of OR-tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CVRP

**What operating system (Linux, Windows, ...) and version?**
Linux: Ubuntu

First Time i'm using this or-tool, examples are really appreciable but with actual location it fail, please check if some thing wrong.

**Comment by arunandroapps** [comment]
DEMANDS = [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
NUM_VEHICLES = 6, ceil value of (TOTAL_PICKUP_LOCATION/CAPACITY_OF_VEHICLE) (22/4)

the model used above is copy of example provided at
https://developers.google.com/optimization/routing/vrp
https://developers.google.com/optimization/routing/cvrp

**Comment by arunandroapps** [comment]
This Error has been solved, can anyone help me with this https://stackoverflow.com/questions/60770400/vehicle-routing-problem-using-or-tools-auto-decide-initial-start-point or i have to generate new ticket in different tab

**Comment by Mizux** [comment]
I'll close this issue then,

For modeling issue please use the mailing list instead to reach the or-tools community,

**Comment by mojojojo20** [comment]
@arunandroapps Hey ! I am facing the same issue as yours. Could you please elaborate on your solution
