### ISSUE TITLE
Error on run TSP sample from docs with version 7.5

### ISSUE THREAD

**Issue by schmittjoaopedro** [google/or-tools#1961]
Environment:
Version: releases/tag/v7.5
Language: Java
Solver: Routing Solver
OS: Windows 10 Home Edition

I'm trying to execute the sample code from google or-tools TSP docs for Java (https://developers.google.com/optimization/routing/tsp#java)

I made the following steps:
* Extracted the zip file (https://github.com/google/or-tools/releases/download/v7.5/or-tools_VisualStudio2019-64bit_v7.5.7466.zip) in my file system (C:\programas\or-tools-vs2019).
* Installed the Visual Studio 2019 Community for C++ local development.
* Created a maven project on IntelliJ (Java)
* Add the dependent or-tools jar libraries in the project (com.google.ortools.jar and protobuf.jar)
* Copied the full TSP Java source code in my project
* Linked the library path `-Djava.library.path=C:\programas\or-tools-vs2019\lib`

However, when I try to run the program, it throws the following error:
```java
Exception in thread "main" java.lang.IllegalAccessError: class com.google.ortools.constraintsolver.RoutingSearchParameters tried to access private field com.google.protobuf.AbstractMessage.memoizedSize (com.google.ortools.constraintsolver.RoutingSearchParameters and com.google.protobuf.AbstractMessage are in unnamed module of loader 'app')
	at com.google.ortools.constraintsolver.RoutingSearchParameters.getSerializedSize(RoutingSearchParameters.java:7367)
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:64)
	at com.google.ortools.constraintsolver.RoutingModel.solveWithParameters(RoutingModel.java:327)
	at com.github.schmittjoaopedro.vrp.ortools.TspCities.main(TspCities.java:92)
```

I expect to run the program as presented in docs.

**Comment by Mizux** [comment]
Hi, which version of Java did you use ?

**Comment by schmittjoaopedro** [comment]
I'm using the following version:

C:\Users\1513 MX5-7>java --version
java 11.0.4 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)

**Comment by schmittjoaopedro** [comment]
I found the error cause. I was using two versions of `protobuff` library, one imported by `ortools` and another one imported from `choco-solver`. Removing the dependency of `choco-solver` fix the issue.

**Comment by Mizux** [comment]
@schmittjoaopedro Wow thanks for the feedback !
Did you know which version of protobuf-java does choco-solver use ?

And I'm sorry, didn't have time to work on it...

**Comment by schmittjoaopedro** [comment]
Sorry, I couldn't find the project again to check the version.
