### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class optimizer.Problem

### ISSUE THREAD

**Issue by bs-hossainy** [google/or-tools#1972]
Hello All, 
I am using the or-tools (CBC solver) in a project. This project is written in Java and has a .exe file which is working fine. But while running the code in my PC (Windows 10, Eclipse IDE, and Tomcat Server 8.5), I get this error: 

Apr 21, 2020 7:21:57 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [OptimizerServlet] in context with path [/jproject] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoClassDefFoundError: Could not initialize class optimizer.Problem
	at optimizer.Optimizer.Optimize(Optimizer.java:5727)
	at OptimizerServlet.doPost(OptimizerServlet.java:3569)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

I tried it with the jniortools.dll version 2016 which is working fine with the .exe file of the same project, as well as the current jniortools version. Both give the same above error. I have already searched StackOverflow and other sources and set and reconfigured the build path but no solution is found yet. 
These are the lines which the error point to inside the code: 

(Optimizer.java:5727) --------->   		problem = new Problem();
(OptimizerServlet.java:3569) ---------->   boolean solved = opt.Optimize();

and this is a part of the Problem class: 

public class Problem {
	
	static { 
		try{
			System.loadLibrary("jniortools"); 
		}
		catch(Exception e){
			System.out.println(e.getMessage());
		}
	}
	MPSolver solver;
	
	public Problem(){
		solver = new MPSolver("JSolver", MPSolver.OptimizationProblemType.CBC_MIXED_INTEGER_PROGRAMMING);
	}

Thank you very much.

**Comment by Mizux** [comment]
could be related to #1779 ?
