### ISSUE TITLE
Sudden crash - PaperMC #214 1.16.3

### ISSUE THREAD

**Issue by filasik** [google/or-tools#2184]
Hello, the server suddenly stops and getting this error:

[crash-2020-10-05_11.44.19-server.txt](https://github.com/google/or-tools/files/5326594/crash-2020-10-05_11.44.19-server.txt)

**Comment by Mizux** [comment]
```sh
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/5/20 11:44 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Could not initialize class com.destroystokyo.paper.event.server.ServerExceptionEvent
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908)
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719)
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202)
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
	at java.lang.Thread.run(Thread.java:748)
```
