### ISSUE TITLE
python_tests_lp_test failed

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#2190]
On master

# Protocol
```sh
cmake -S. -Bbuild -DBUILD_PYTHON=ON -DBUILD_CXX_SAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF
cmake --build build -v -j16
...
cd build
export CTEST_OUTPUT_ON_FAILURE=1
ctest -R "python_tests_lp"
```

# Observed
```sh
Test project /home/mizux/work/master/build
    Start 239: python_tests_lp_test
1/1 Test #239: python_tests_lp_test .............***Failed    0.13 sec
WARNING: Logging before InitGoogleLogging() is written to STDERR
1/1 Test #239: python_tests_lp_test .............***Failed    0.13 sec
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1007 20:48:14.137678 49756 linear_solver.cc:279] Reduced cost only available for continuous problems
E1007 20:48:14.137701 49756 linear_solver.cc:279] Reduced cost only available for continuous problems
E1007 20:48:14.137706 49756 linear_solver.cc:137] Dual value only available for continuous problems
E1007 20:48:14.137708 49756 linear_solver.cc:137] Dual value only available for continuous problems
E1007 20:48:14.141502 49756 linear_solver.cc:279] Reduced cost only available for continuous problems
E1007 20:48:14.141512 49756 linear_solver.cc:279] Reduced cost only available for continuous problems
E1007 20:48:14.141517 49756 linear_solver.cc:137] Dual value only available for continuous problems
E1007 20:48:14.141523 49756 linear_solver.cc:137] Dual value only available for continuous problems
E1007 20:48:14.142457 49756 bop_interface.cc:256] Number of iterations not available
E1007 20:48:14.142465 49756 linear_solver.cc:279] Reduced cost only available for continuous problems
E1007 20:48:14.142469 49756 linear_solver.cc:279] Reduced cost only available for continuous problems
E1007 20:48:14.142475 49756 linear_solver.cc:137] Dual value only available for continuous problems
E1007 20:48:14.144450 49756 linear_solver.cc:1457] Objective value 0.5 isn't accurate, it should be 1 (delta=0.5).
E1007 20:48:14.144461 49756 linear_solver.cc:1470] There were 1 errors above the tolerance (1e-07), the largest was 0.5
W1007 20:48:14.144750 49756 integral_solver.cc:628] A constraint is trivially unsatisfiable.
E1007 20:48:14.144814 49756 integral_solver.cc:923] Constraint 0 out of bound: 0  should be in 20 .. inf
...
======================================================================
FAIL: testApi (__main__.PyWrapLpTest) [SAT_INTEGER_PROGRAMMING: 14]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mizux/work/master/examples/tests/lp_test.py", line 192, in testApi
    self.RunBooleanExampleCppStyleAPI(problem_type)
  File "/home/mizux/work/master/examples/tests/lp_test.py", line 129, in RunBooleanExampleCppStyleAPI
    self.SolveAndPrint(solver, [x1, x2], [c0])
  File "/home/mizux/work/master/examples/tests/lp_test.py", line 143, in SolveAndPrint
    assert solver.VerifySolution(1e-7, True)
AssertionError

----------------------------------------------------------------------
Ran 4 tests in 0.012s

FAILED (failures=1)
...
------ Boolean programming example with SAT_INTEGER_PROGRAMMING ------

*** C++ style API ***
Number of variables = 2
Number of constraints = 1
testBopInfeasible
0
testSetHint
swig/python detected a memory leak of type 'absl::Status *', no destructor found.


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.13 sec

The following tests FAILED:
	239 - python_tests_lp_test (Failed)
Errors while running CTest
```

**Comment by Mizux** [comment]
```sh
[0]─[~/work/master]
[^v^]─mizux@nuc10i7 %grepc -rIin "a memory leak of type " build
build/Testing/Temporary/LastTest.log:191:swig/python detected a memory leak of type 'absl::Status *', no destructor found.
build/python/ortools/data/rcpspPYTHON_wrap.cxx:1585:      printf("swig/python detected a memory leak of type '%s', no destructor found.\n", (name ? name : "unknown"));
build/python/ortools/algorithms/knapsack_solverPYTHON_wrap.cxx:1585:      printf("swig/python detected a memory leak of type '%s', no destructor found.\n", (name ? name : "unknown"));
build/python/ortools/sat/satPYTHON_wrap.cxx:1587:      printf("swig/python detected a memory leak of type '%s', no destructor found.\n", (name ? name : "unknown"));
build/python/ortools/util/sorted_interval_listPYTHON_wrap.cxx:1585:      printf("swig/python detected a memory leak of type '%s', no destructor found.\n", (name ? name : "unknown"));
build/python/ortools/constraint_solver/routingPYTHON_wrap.cxx:1586:      printf("swig/python detected a memory leak of type '%s', no destructor found.\n", (name ? name : "unknown"));
build/python/ortools/graph/graphPYTHON_wrap.cxx:1585:      printf("swig/python detected a memory leak of type '%s', no destructor found.\n", (name ? name : "unknown"));
build/python/ortools/linear_solver/linear_solverPYTHON_wrap.cxx:1585:      printf("swig/python detected a memory leak of type '%s', no destructor found.\n", (name ? name : "unknown"));
```

**Comment by Mizux** [comment]
Seems to come from LoadSolutionFromProto()
https://github.com/google/or-tools/blob/f87dc09b7e042eb6f283f44705b083df3c336ac3/examples/tests/lp_test.py#L231-L233

swig generated file:
```
[0]─[~/work/master]
[^v^]─mizux@nuc10i7 %grepc "absl::Status" -C10 build/python/ortools/linear_solver/linear_solverPYTHON_wrap.cxx

SWIGINTERN PyObject *_wrap_Solver_LoadSolutionFromProto__SWIG_0(PyObject *SWIGUNUSEDPARM(self), Py_ssize_t nobjs, PyObject **swig_obj) {
  PyObject *resultobj = 0;
  operations_research::MPSolver *arg1 = (operations_research::MPSolver *) 0 ;
  operations_research::MPSolutionResponse *arg2 = 0 ;
  double arg3 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  double val3 ;
  int ecode3 = 0 ;
  absl::Status result;
  
  if ((nobjs < 3) || (nobjs > 3)) SWIG_fail;
  res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_operations_research__MPSolver, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Solver_LoadSolutionFromProto" "', argument " "1"" of type '" "operations_research::MPSolver *""'"); 
  }
  arg1 = reinterpret_cast< operations_research::MPSolver * >(argp1);
  {
    arg2 = new operations_research::MPSolutionResponse;
    PyObject* const pyresult = PyObject_CallMethod(
--
      }
      Py_DECREF(pyresult);
    }
  }
  ecode3 = SWIG_AsVal_double(swig_obj[2], &val3);
  if (!SWIG_IsOK(ecode3)) {
    SWIG_exception_fail(SWIG_ArgError(ecode3), "in method '" "Solver_LoadSolutionFromProto" "', argument " "3"" of type '" "double""'");
  } 
  arg3 = static_cast< double >(val3);
  result = (arg1)->LoadSolutionFromProto((operations_research::MPSolutionResponse const &)*arg2,arg3);
  resultobj = SWIG_NewPointerObj((new absl::Status(static_cast< const absl::Status& >(result))), SWIGTYPE_p_absl__Status, SWIG_POINTER_OWN |  0 );
  {
    delete arg2;
  }
  return resultobj;
fail:
  {
    delete arg2;
  }
  return NULL;
}


SWIGINTERN PyObject *_wrap_Solver_LoadSolutionFromProto__SWIG_1(PyObject *SWIGUNUSEDPARM(self), Py_ssize_t nobjs, PyObject **swig_obj) {
  PyObject *resultobj = 0;
  operations_research::MPSolver *arg1 = (operations_research::MPSolver *) 0 ;
  operations_research::MPSolutionResponse *arg2 = 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  absl::Status result;
  
  if ((nobjs < 2) || (nobjs > 2)) SWIG_fail;
  res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_operations_research__MPSolver, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Solver_LoadSolutionFromProto" "', argument " "1"" of type '" "operations_research::MPSolver *""'"); 
  }
  arg1 = reinterpret_cast< operations_research::MPSolver * >(argp1);
  {
    arg2 = new operations_research::MPSolutionResponse;
    PyObject* const pyresult = PyObject_CallMethod(
--
      char* buffer = nullptr;
      Py_ssize_t length = 0;
      int result = PyString_AsStringAndSize(pyresult, &buffer, &length);
      if (buffer != nullptr) {
        arg2->ParseFromArray(buffer, length);
      }
      Py_DECREF(pyresult);
    }
  }
  result = (arg1)->LoadSolutionFromProto((operations_research::MPSolutionResponse const &)*arg2);
  resultobj = SWIG_NewPointerObj((new absl::Status(static_cast< const absl::Status& >(result))), SWIGTYPE_p_absl__Status, SWIG_POINTER_OWN |  0 );
  {
    delete arg2;
  }
  return resultobj;
fail:
  {
    delete arg2;
  }
  return NULL;
}
--
	 { NULL, NULL, 0, NULL }
};

static PyMethodDef SwigMethods_proxydocs[] = {
	 { NULL, NULL, 0, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_absl__Status = {"_p_absl__Status", "absl::Status *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_char = {"_p_char", "char *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_int = {"_p_int", "int *|int_least32_t *|int32 *|int32_t *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_long = {"_p_long", "intptr_t *|int_least64_t *|int_fast32_t *|int_fast64_t *|int64 *|int64_t *|long *|int_fast16_t *|intmax_t *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_operations_research__MPConstraint = {"_p_operations_research__MPConstraint", "operations_research::MPConstraint *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_operations_research__MPModelExportOptions = {"_p_operations_research__MPModelExportOptions", "operations_research::MPModelExportOptions *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_operations_research__MPModelRequest = {"_p_operations_research__MPModelRequest", "operations_research::MPModelRequest *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_operations_research__MPObjective = {"_p_operations_research__MPObjective", "operations_research::MPObjective *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_operations_research__MPSolver = {"_p_operations_research__MPSolver", "operations_research::MPSolver *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_operations_research__MPSolverParameters = {"_p_operations_research__MPSolverParameters", "operations_research::MPSolverParameters *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_operations_research__MPVariable = {"_p_operations_research__MPVariable", "operations_research::MPVariable *", 0, 0, (void*)0, 0};
```

**Comment by Mizux** [comment]
I gues these method should return a bool i.e. `return result.ok()`
