### ISSUE TITLE
SWIG Exceptionon Windows when trying to create a RoutingModel 

### ISSUE THREAD

**Issue by mslazynski** [google/or-tools#2208]
Version: 8.0.8283
Language: C#

I'm using the Routing Solver in a crossplatform project. While executed from macOS/Linux, everything works fine, on Windows I get an exception while trying to create a RoutingModel. 

```
The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception. :
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.new_RoutingIndexManager__SWIG_1(Int32 jarg1, Int32 jarg2, Int32 length3, Int32[] jarg3, Int32 length4, Int32[] jarg4)
   at Google.OrTools.ConstraintSolver.RoutingIndexManager..ctor(Int32 num_nodes, Int32 num_vehicles, Int32[] starts, Int32[] ends)
```

All machines are using the current stable .netcore 3.1, the Windows machine runs Windows Server 2016 (1607).

**Comment by Mizux** [comment]
Can you show us the source ?
Did you manage to run some examples ?

It seems it is the ctor of `RoutingIndexManager` than RoutingModel;

**Comment by mslazynski** [comment]
Yup, you're right, it's the `RoutingIndexImanager`.

As for the source code, I am not allowed to share much, but the line building the index manager looks like this:

```
Manager = new RoutingIndexManager(
                        Problem.NumberOfEndpoints,
                        Problem.NumberOfVehicles,
                        Problem.Vehicles.Select(v => (int)v.Start.Index).ToArray(),
                        Problem.Vehicles.Select(v => (int)v.Finish.Index).ToArray()
                    );
```
, where, according to the debugger in this specific case:

- `Problem.NumberOfEndpoints` is an {int} with value {27}
- `Problem.NumberOfVehicles` is an {int} with value {40}
- `Problem.Vehicles.Select(v => (int)v.Start.Index).ToArray()` is `{int[40}` with values `25` or `26` only
- `Problem.Vehicles.Select(v => (int)v.Finish.Index).ToArray()` is `{int[40}` with values `25` or `26` only

I'll try to run the examples and get back to you ASAP.

**Comment by mslazynski** [comment]
OK. So I've tried with the example `cscvrptw.csproj`. I got similar, but more detailed error on Windows. There is some kind of problem with loading `google-ortools-native` dll. It's there but probably some depedencies are missing. I'm building the project using `dotnet publish -r win-x64` on macOS machine. I will try to track missing depedencies...

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'google-ortools-native' or one of its dependencies: Nie można odnaleźć określonego modułu. (Exception from HRESULT: 0x8007007E)
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_constraint_solver(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.new_RoutingIndexManager__SWIG_1(Int32 jarg1, Int32 jarg2, Int32 length3, Int32[] jarg3, Int32 length4, Int32[] jarg4)
   at CapacitatedVehicleRoutingProblemWithTimeWindows.Solve(Int32 number_of_orders, Int32 number_of_vehicles) in /Users/msl/Projects/optidata/or-tools/examples/dotnet/cscvrptw.cs:line 243
   at CapacitatedVehicleRoutingProblemWithTimeWindows.Main(String[] args) in /Users/msl/Projects/optidata/or-tools/examples/dotnet/cscvrptw.cs:line 367
```

**Comment by Mizux** [comment]
> using `dotnet publish -r win-x64` on macOS machine.

don't get it

**Comment by mslazynski** [comment]
`dotnet publish` is a neat way to build deployable C# packages with all the dependencies (in theory). It's able to produce builds for different platforms from the command line...  Apparently it somehow doesn't handle the OrTools well enough, which is weird because the `Google.OrTools.dll` gets loaded with no issues.
 
I'll try to build the thing in the Windows docker...

**Comment by mslazynski** [comment]
OK. I've managed to fix the issue. The problem was a missing DLL dependency for `google-ortools-native.dll`: `VCRUNTIME140_1.dll`. Apparently older installers of the Visual Studio Redistributable missed this file by mistake...

Thanks for your time and assistance!

**Comment by Mizux** [comment]
Thanks for the feedback !
