### ISSUE TITLE
Error running examples/python/tsp.py on OSX

### ISSUE THREAD

**Issue by cwelton** [google/or-tools#221]
1. Downloaded or-tools from https://github.com/google/or-tools/releases/tag/v4.2
2. Installed or-tools with `python setup.py install --user`
3. Run the TSP example:
```
bash$  python --version
Python 2.7.10

bash$  python examples/python/tsp.py 
Traceback (most recent call last):
  File "examples/python/tsp.py", line 32, in <module>
    from ortools.constraint_solver import routing_enums_pb2
  File "/Users/cwelton/Library/Python/2.7/lib/python/site-packages/ortools-4.2.3790-py2.7-macosx-10.6-intel.egg/ortools/constraint_solver/routing_enums_pb2.py", line 22, in <module>
    serialized_pb=_b('\n-ortools/constraint_solver/routing_enums.proto\x12\x13operations_research\"\xde\x02\n\x15\x46irstSolutionStrategy\"\xc4\x02\n\x05Value\x12\r\n\tAUTOMATIC\x10\x00\x12\x15\n\x11PATH_CHEAPEST_ARC\x10\x03\x12\x1d\n\x19PATH_MOST_CONSTRAINED_ARC\x10\x04\x12\x16\n\x12\x45VALUATOR_STRATEGY\x10\x05\x12\x0b\n\x07SAVINGS\x10\n\x12\t\n\x05SWEEP\x10\x0b\x12\x10\n\x0c\x43HRISTOFIDES\x10\r\x12\x13\n\x0f\x41LL_UNPERFORMED\x10\x06\x12\x12\n\x0e\x42\x45ST_INSERTION\x10\x07\x12\x1f\n\x1bPARALLEL_CHEAPEST_INSERTION\x10\x08\x12\x1c\n\x18LOCAL_CHEAPEST_INSERTION\x10\t\x12\x17\n\x13GLOBAL_CHEAPEST_ARC\x10\x01\x12\x16\n\x12LOCAL_CHEAPEST_ARC\x10\x02\x12\x1b\n\x17\x46IRST_UNBOUND_MIN_VALUE\x10\x0c\"\x89\x01\n\x18LocalSearchMetaheuristic\"m\n\x05Value\x12\r\n\tAUTOMATIC\x10\x00\x12\x12\n\x0eGREEDY_DESCENT\x10\x01\x12\x17\n\x13GUIDED_LOCAL_SEARCH\x10\x02\x12\x17\n\x13SIMULATED_ANNEALING\x10\x03\x12\x0f\n\x0bTABU_SEARCH\x10\x04\x42I\n#com.google.ortools.constraintsolverP\x01\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by dlahlou** [comment]
Hello cwelton,
As discussed in this [issue](https://github.com/google/or-tools/issues/207), this error is due to an old version of protobuf that is binding the one installed by ortools. To fix this, I can suggest two options : 

1. Remove the old version like so, you will have first to find the path to the old version like so : 
```
python
import google.protobuf, inspect
inspect.getfile(google.protobuf)
ctrl+d
```
and then remove it from your system.
2. Prioritize the new version of protobuf using PYTHONPATH :
`PYTHONPATH=path_to_protobuf3.0.0 python tsp.py`
You can find the path_to_protobuf3.0.0 by retyping `python setup.py install --user`.

I hope this helps.

--

driss

**Comment by cwelton** [comment]
Okay... this is a little weird, but what worked for me was
```
pip uninstall protobuf
pip uninstall protobuf
pip install protobuf
```
Somehow I had two different versions of protobuf installed so uninstalling it twice got me down to no versions, then reinstalling got me to a sane state with protobuf 3.

**Comment by antoniomedrano** [comment]
I experienced this as well
