### ISSUE TITLE
cvrptw example fails when sameStartFinish=False

### ISSUE THREAD

**Issue by cwelton** [google/or-tools#226]
Updating the single line:

```
   start_fn = vehicles.return_starting_callback(customers,
                                                 sameStartFinish=True)
```

to

```
   start_fn = vehicles.return_starting_callback(customers,
                                                 sameStartFinish=False)
```

Results in:

```
Traceback (most recent call last):
  File "/Users/cwelton/projects/ortools/ortools_python/examples/python/cvrptw.py", line 740, in <module>
    main()
  File "/Users/cwelton/projects/ortools/ortools_python/examples/python/cvrptw.py", line 676, in main
    cust.tw_close.seconds)
  File "/Users/cwelton/Library/Python/2.7/lib/python/site-packages/ortools/constraint_solver/pywrapcp.py", line 1339, in SetRange
    return _pywrapcp.IntExpr_SetRange(self, l, u)
Exception: CP Solver fail
```

Similar results in other tests I've tried running when using an end depot array that contains nodes not in the start depot list.

**Comment by furnon** [comment]
Code sample fixed and submitted (btw the file was renamed cvrptw_plot.py a
couple of weeks ago). Management of node/variable indices wasn't properly
done in the example.

**Comment by Grovespaz** [comment]
Does that mean this can be closed?

**Comment by cwelton** [comment]
That was my interpretation.
