### ISSUE TITLE
Error with SetArcCostEvaluatorOfVehicle

### ISSUE THREAD

**Issue by FreddyHunter** [google/or-tools#2609]
**What version of OR-Tools and what language are you using?**
Version: latest
Language: Python

**Which solver are you using: Routing Solver

**What operating system and version? Linux Ubuntu 20.04

**What did you do?**
I modeled the total cost (fixed and variable) per vehicle to be included at objective function, as you can see below:
```python
    # Add Costs constraint.
    def create_cost_callback(data, vehicle_id):
        """Created call back to get total cost between locations """
#        def service_cost(from_index):
#            """ Gets the service cost for the specified location."""
#            return data["demands"][node]*data["cost_per_demand_unit"]

        def travel_cost(from_index, to_index, vehicle_id):
            """Gets the travel cost between two locations """
            # Convert from routing variable Index to time matrix NodeIndex.
            from_node = manager.IndexToNode(from_index)
            to_node = manager.IndexToNode(to_index)
            travel_cost = (data['vehicle_fix_costs'][vehicle_id] + data['distance_matrix'][from_node][to_node] * data['vehicle_var_costs'][vehicle_id])

        def cost_callback(from_index, to_index):
            """ Returns the total costs between the two nodes """
#            serv_cost = service_cost(from_node)
            trav_cost = travel_cost(from_index, to_index, vehicle_id)
            return trav_cost #+ serv_cost

        return cost_callback

    for vehicle_id in range(data['num_vehicles']):
        print(vehicle_id)
        print(int(vehicle_id))
        cost_callback = create_cost_callback(data, int(vehicle_id))
        routing.SetArcCostEvaluatorOfVehicle(cost_callback, int(vehicle_id))
```
**What did you expect to see**
During optimization I want optimizer select first the cheapest vehicles and than move forward to orders, considering the others constraints included.

**What did you see instead?**

I got the following error:
```sh
Traceback (most recent call last):
  File "optim_test9.py", line 845, in <module>
    main_optimizer()
  File "optim_test9.py", line 493, in main_optimizer
    routing.SetArcCostEvaluatorOfVehicle(cost_callback, int(vehicle_id))
  File "/usr/local/lib/python3.8/dist-packages/ortools/constraint_solver/pywrapcp.py", line 5212, in SetArcCostEvaluatorOfVehicle
    return _pywrapcp.RoutingModel_SetArcCostEvaluatorOfVehicle(self, evaluator_index, vehicle)
TypeError: in method 'RoutingModel_SetArcCostEvaluatorOfVehicle', argument 2 of type 'int'
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
you didn't "register"  your callback...
