### ISSUE TITLE
TypeError with scip

### ISSUE THREAD

**Issue by whoknowsname** [google/or-tools#2655]
**What version of OR-Tools and what language are you using?**
Version: master
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
macOS
10.13

**What did you do?**
run the following code:
```
from openpyxl import load_workbook
from ortools.linear_solver import pywraplp

import calDistance


fixed_point = [113.233, 23.166]


wb = load_workbook("isolatedPoints.xlsx")
ws = wb["pointInfo"]
last_row = ws.max_row

weight_demand_list = []
for i in range(1, last_row + 1):
    weight_demand_list.append(ws.cell(i, 1).value)


point_longitude_latitude_list = []
for i in range(1, last_row + 1):
    point = [ws.cell(i, 2).value, ws.cell(i, 3).value]
    point_longitude_latitude_list.append(point)

point_number = last_row


distance_list = []
for i in range(point_number):
    d = calDistance.geo_distance(point_longitude_latitude_list[i], fixed_point)
    distance_list.append(d)


load_list = [5000, 16000, 30000]
cost_per_km_list = [3.5, 6, 9]
vehicle_type_number = len(load_list)

vehicle_cost_list = []
for i in range(point_number):
    d = distance_list[i]
    cost = []
    for j in range(vehicle_type_number):
        cost.append(d * cost_per_km_list[j])
    vehicle_cost_list.append(cost)

solver = pywraplp.Solver.CreateSolver("SCIP")
infinity = solver.infinity()

vehicle_number = {}
for i in range(point_number):
    for j in range(vehicle_type_number):
        vehicle_number[(i, j)] = solver.IntVar(0.0, infinity, "vehicle_number_{}_{}".format(i, j))

for i in range(point_number):
    expr = [vehicle_number[(i, j)] * load_list[j] for j in range(vehicle_type_number)]
    solver.Add(solver.Sum(expr) >= weight_demand_list[i])

obj_expr = []
for i in range(point_number):
    for j in range(vehicle_type_number):
        obj_expr.append(vehicle_number[(i, j)] * vehicle_cost_list[j]) //line 74 is here

solver.Minimize(solver.Sum(obj_expr))
status = solver.Solve()

if status == pywraplp.Solver.OPTIMAL:
    print('Objective value =', solver.Objective().Value())
    print('Problem solved in %f milliseconds' % solver.wall_time())
    print('Problem solved in %d iterations' % solver.iterations())
    print('Problem solved in %d branch-and-bound nodes' % solver.nodes())
else:
    print('The problem does not have an optimal solution.')
```

**What did you expect to see**
objective value

**What did you see instead?**
```
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/express/isolatedPointsModel.py", line 74, in <module>
    obj_expr.append(vehicle_number[(i, j)] * vehicle_cost_list[j])
  File "/Users/admin/.conda/envs/express/lib/python3.9/site-packages/ortools/linear_solver/pywraplp.py", line 1056, in <lambda>
    lambda self, *args: getattr(VariableExpr(self), opname)(*args))
  File "/Users/admin/.conda/envs/express/lib/python3.9/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 116, in __mul__
    return ProductCst(self, cst)
  File "/Users/admin/.conda/envs/express/lib/python3.9/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 178, in __init__
    raise TypeError
TypeError
```

**Comment by whoknowsname** [comment]
sry, my code has something wrong, i have fixed it.

**Comment by whoknowsname** [comment]
sry
the code has something wrong, i have fixed it.
