### ISSUE TITLE
Problem using Java library

### ISSUE THREAD

**Issue by amc6** [google/or-tools#272]
I am running into issues using the or-tool library with Java bindings. We have one class and one test that uses MPSolver. When the test is run by itself everything works, but the VM crashes when run as part of the test suite. Through both stepping through with a debugger and by using print lines, I have determined that the JVM is crashing with a SIGILL when our code calls MPSolver.solve.

I am running this on OSX 10.11.6.  I am using the prebuilt libraries. But the only files I am including in the build are libjniortools.jnilib and the ortools jar. Is this correct set of files to include?

Intellij just gives me this error:
```
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```
But maven provides a bit more:
```
/bin/sh: line 1: 10427 Illegal instruction: 4  /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/bin/java -javaagent:/Users/adamcook/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/adamcook/code/algorithm/target/jacoco.exec -jar /Users/adamcook/code/algorithm/target/surefire/surefirebooter7894310666470673198.jar /Users/adamcook/code/algorithm/target/surefire/surefire6683140905464024423tmp /Users/adamcook/code/algorithm/target/surefire/surefire_04135778575773710503tmp

Results :

Tests run: 201, Failures: 0, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:35 min
[INFO] Finished at: 2016-11-14T16:54:22-08:00
[INFO] Final Memory: 28M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project foxtrot-algorithm: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project foxtrot-algorithm: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.close(ForkClient.java:257)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:301)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:116)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:740)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAllProviders(AbstractSurefireMojo.java:682)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:648)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:586)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by amc6** [comment]
Actually all of the .dynlib files are also in the same directory as the .jnilib file. But they aren't referenced from Java or maven in any way.

**Comment by evanfields** [comment]
This issue appears to be limited to Cbc - using GLPK as our MIP solver sidestepped the issue. We're not sure if the problem originates in Cbc or or-tools, though I note we were able to solve some MIP problems with Cbc accessed via JuMP and Julia.

**Comment by bamine** [comment]
Did somebody find the source of the problem ?

**Comment by Plastix** [comment]
I have the exact same issue on MacOS 10.12.6 using the prebuilt libraries. I'm using the Java bindings with `MPSolver` and the default CBC solver with a single Java class. However, my code crashes whenever I try to tell the solver to solve the optimization problem.

Gradle reports the following error:
```
* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java'' finished with non-zero exit value 132
```

Running without Gradle produces the following error:
```
[1]    12943 illegal hardware instruction  java -Djava.library.path=libs -Dfile.encoding=UTF-8 -Duser.country=US   -cp 
```
It seems that the error only occurs when I'm setting a lot of coefficients (~100k) to a single constraint.

**Comment by nooshin-mirzadeh** [comment]
Any update on this bug? I have the same issue!

**Comment by uluyol** [comment]
This happens to me with less than 100% reliability. I get runs with SIGILL but no stacktrace, SIGILL with stacktrace, and some successful runs. My program is not using any threads, so if there is a race, it isn't in my code.

**Comment by roborobotheart** [comment]
Same issue too. Just get "Process finished with exit code 132 (interrupted by signal 4: SIGILL)" when run "model.solve()". And I tried to re-install ortools and chose "Installing OR-Tools Java from Source". New library works.

**Comment by lperron** [comment]
I know.
I have no way to fix that. There is an incompatibility between Java and the CBC code (I believe when solving in parallel).

**Comment by luca-filipponi** [comment]
@roborobotheart can you explain how you solved? I've tried to build the sources from latest stable and then use what was inside lib in the classpath but i'm getting other errors. Which version is working for you?

**Comment by luca-filipponi** [comment]
I've updgraded from java 12 to java 13 and the problem is solved.
