### ISSUE TITLE
importing routing_enums_pb2 throws AttributeError

### ISSUE THREAD

**Issue by tvwenger** [google/or-tools#3202]
**What version of OR-Tools and what language are you using?**
```
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ortools
>>> print(ortools.__version__)
9.3.10497
```

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
```
$ uname -a
Linux Jansky 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**What did you do?**
```
$ python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ortools
>>> print(ortools.__version__)
9.3.10497
>>> from ortools.constraint_solver import routing_enums_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/twenger/maxfieldenv/lib/python3.9/site-packages/ortools-9.3.10497-py3.9-linux-x86_64.egg/ortools/constraint_solver/routing_enums_pb2.py", line 21, in <module>
    _FIRSTSOLUTIONSTRATEGY = DESCRIPTOR.message_types_by_name['FirstSolutionStrategy']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

**What did you expect to see**
No AttributeError

**What did you see instead?**
An AttributeError

**Anything else we should know about your project / environment**
Seems to work in an older version of ortools:
```
$ python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ortools
>>> print(ortools.__version__)
8.2.8710
>>> from ortools.constraint_solver import routing_enums_pb2
```

**Comment by lperron** [comment]
can you check the installed version of protobuf ?

**Comment by tvwenger** [comment]
```
$ pip install --upgrade protobuf
Requirement already satisfied: protobuf in ./lib/python3.9/site-packages/protobuf-4.0.0rc2-py3.9.egg (4.0.0rc2)
Requirement already satisfied: setuptools in ./lib/python3.9/site-packages (from protobuf) (57.4.0)
Requirement already satisfied: six>=1.9 in ./lib/python3.9/site-packages/six-1.16.0-py3.9.egg (from protobuf) (1.16.0
```

**Comment by stradivari96** [comment]
Yep, try with `pip install "protobuf<4.0"`

**Comment by tvwenger** [comment]
No issues with `protobuf` 3.19.4. Looks like the requirements requests `protobuf>=3.19.4`, which is why pip is going after 4.0.
