### ISSUE TITLE
Several tests fail due to omitted solvers

### ISSUE THREAD

**Issue by StefanBruens** [google/or-tools#3261]
Several test cases fail, probably due to omitted solvers (see cmake options below):

E.g.:
```
[  471s]  34/382 Test  #35: python_linear_solver_integer_programming_example ...........................***Failed    0.07 sec
[  471s] WARNING: Logging before InitGoogleLogging() is written to STDERR
[  471s] W0425 17:27:14.790188 31828 linear_solver.cc:621] Support for SCIP not linked in, or the license was not found.
[  471s] Traceback (most recent call last):
[  471s]   File "/home/abuild/rpmbuild/BUILD/or-tools-9.3/ortools/linear_solver/samples/integer_programming_example.py", line 77, in <module>
[  471s]     IntegerProgrammingExample()
[  471s]   File "/home/abuild/rpmbuild/BUILD/or-tools-9.3/ortools/linear_solver/samples/integer_programming_example.py", line 31, in IntegerProgrammingExample
[  471s]     x = solver.IntVar(0.0, solver.infinity(), 'x')
[  471s] AttributeError: 'NoneType' object has no attribute 'IntVar'
```

Or:
```
[  570s] 363/382 Test #358: cxx_tests_issue173 .........................................................Subprocess aborted***Exception:   5.17 sec
[  570s] WARNING: Logging before InitGoogleLogging() is written to STDERR
[  570s] F0425 17:28:48.265081   638 linear_solver.cc:435] Linear solver not recognized.
[  570s] *** Check failure stack trace: ***
```

Summary:
```
[  573s] 93% tests passed, 28 tests failed out of 382
[  573s] 
[  573s] Total Test time (real) = 102.50 sec
[  573s] 
[  573s] The following tests FAILED:
[  573s]         29 - python_linear_solver_assignment_groups_mip (Failed)
[  573s]         30 - python_linear_solver_assignment_mip (Failed)
[  573s]         31 - python_linear_solver_assignment_task_sizes_mip (Failed)
[  573s]         32 - python_linear_solver_assignment_teams_mip (Failed)
[  573s]         34 - python_linear_solver_bin_packing_mip (Failed)
[  573s]         35 - python_linear_solver_integer_programming_example (Failed)
[  573s]         37 - python_linear_solver_mip_var_array (Failed)
[  573s]         40 - python_linear_solver_simple_mip_program (Failed)
[  573s]        167 - python_contrib_3_jugs_mip (Subprocess aborted)
[  573s]        174 - python_contrib_assignment6_mip (Subprocess aborted)
[  573s]        175 - python_contrib_blending (Subprocess aborted)
[  573s]        183 - python_contrib_coins_grid_mip (Subprocess aborted)
[  573s]        184 - python_contrib_coloring_ip (Subprocess aborted)
[  573s]        197 - python_contrib_diet1_mip (Subprocess aborted)
[  573s]        208 - python_contrib_game_theory_taha (Subprocess aborted)
[  573s]        216 - python_contrib_knapsack_mip (Subprocess aborted)
[  573s]        220 - python_contrib_least_square (Subprocess aborted)
[  573s]        225 - python_contrib_magic_square_mip (Subprocess aborted)
[  573s]        248 - python_contrib_production (Subprocess aborted)
[  573s]        279 - python_contrib_stigler_contrib (Subprocess aborted)
[  573s]        286 - python_contrib_volsay (Subprocess aborted)
[  573s]        287 - python_contrib_volsay2 (Subprocess aborted)
[  573s]        288 - python_contrib_volsay3 (Subprocess aborted)
[  573s]        315 - python_python_appointments (Subprocess aborted)
[  573s]        343 - python_python_steel_mill_slab_sat (Subprocess aborted)
[  573s]        358 - cxx_tests_issue173 (Subprocess aborted)
[  573s]        363 - python_tests_dual_loading (Subprocess aborted)
[  573s]        377 - python_tests_pywraplp_test (Subprocess aborted)
[  573s] Errors while running CTest
[  573s] error: Bad exit status from /var/tmp/rpm-tmp.nDJlop (%check)

```

Version: v9.3

**What operating system (Linux, Windows, ...) and version?**
Linux, GCC 11.2.1, Python 3.8.

**What did you do?**
```
cmake -B build -S . \
  -DBUILD_DEPS:BOOL=OFF \
  -DBUILD_pybind11:BOOL=OFF \
  -DBUILD_PYTHON:BOOL=ON \
  -DVENV_USE_SYSTEM_SITE_PACKAGES:BOOL=ON \
  -DUSE_SCIP:BOOL=OFF \
  -DUSE_COINOR:BOOL=OFF
make
make install
ctest
```

Test depending on e.g. SCIP should obviously be skipped.

TODO(mizux):
* [x] Fix C++ tests
* [x] Fix .Net tests
* [x] Fix Java tests
* [x] Fix Python tests

**Comment by StefanBruens** [comment]
This has regressed, the following commit added two test with a hard, unchecked dependency on SCIP:
https://github.com/google/or-tools/commit/542ec76a8a9cff27bcd792f890dcdad0dfe6ca3b

(N.b. I have seen SCIP is now OSI compliant.)

**Comment by StefanBruens** [comment]
For running pytest tests from CTest, you should probably consider using https://pypi.org/project/pytest-cmake/

**Comment by StefanBruensLC** [comment]
> This has regressed, the following commit added two test with a hard, unchecked dependency on SCIP: [542ec76](https://github.com/google/or-tools/commit/542ec76a8a9cff27bcd792f890dcdad0dfe6ca3b)
> 
> (N.b. I have seen SCIP is now OSI compliant.)

Probably fixed with https://github.com/google/or-tools/commit/49c8f26ef20b28b401c599b9ce2db4e644080f6d
