### ISSUE TITLE
CMake GLPK build is broken

### ISSUE THREAD

**Issue by jashandeep-sohi** [google/or-tools#3312]
Hi, looks like building with GLPK support using CMake is broken. Getting errors about undefined symbols for `SetupGlpkEnvAutomaticDeletion`.

**What version of OR-Tools and what language are you using?**
Version: `v9.3`
Language: `Python 3.9`

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
```pywraplp.Solver.CreateSolver("GLPK")```

**What operating system (Linux, Windows, ...) and version?**
`Debian Bullseye`

**What did you do?**
```shell
$ apt-get install --no-install-recommends -y \
      git ninja-build pkg-config build-essential autoconf libtool lsb-release ccache

# build or-tools
$ cmake -S. -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_DEPS=ON -DUSE_GLPK=ON -DBUILD_GLPK=ON -DBUILD_FLATZINC=OFF \
    -DBUILD_PYTHON=ON -DBUILD_SAMPLES=OFF -DBUILD_EXAMPLES=OFF \
    -DBUILD_TESTING=OFF -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
  && cmake --build build --parallel 8 -v

# smoke test
$ pip install build/python/dist/*.whl \
  && python -c "from ortools.linear_solver import pywraplp as p; p.Solver.CreateSolver('SCIP')" \
  && python -c "from ortools.linear_solver import pywraplp as p; p.Solver.CreateSolver('GLPK')"
```

**What did you expect to see**
Nothing :)

**What did you see instead?**
```shell
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/src/or-tools/build/python/ortools/linear_solver/pywraplp.py", line 13, in <module>
from . import _pywraplp
ImportError: /src/or-tools/build/python/ortools/linear_solver/../../ortools/.libs/libortools.so.9: undefined symbol: _ZN19operations_research29SetupGlpkEnvAutomaticDeletionEv
```

**Anything else we should know about your project / environment**

I was able to come up with a patch that fixes the undefined symbols. If it looks reasonable I can submit a PR.
```diff
diff --git a/cmake/cpp.cmake b/cmake/cpp.cmake
index 414d878242..dbef70ecad 100644
--- a/cmake/cpp.cmake
+++ b/cmake/cpp.cmake
@@ -27,6 +27,7 @@ if(USE_COINOR)
 endif()
 if(USE_GLPK)
   list(APPEND OR_TOOLS_COMPILE_DEFINITIONS "USE_GLPK")
+  set(GLPK_DIR glpk)
 endif()
 if(USE_PDLP)
   list(APPEND OR_TOOLS_COMPILE_DEFINITIONS "USE_PDLP")
@@ -226,6 +227,7 @@ foreach(SUBPROJECT IN ITEMS
  constraint_solver
  ${PDLP_DIR}
  ${GSCIP_DIR}
+ ${GLPK_DIR}
  glop
  graph
  gurobi
diff --git a/ortools/glpk/CMakeLists.txt b/ortools/glpk/CMakeLists.txt
new file mode 100644
index 0000000000..25e25f38f4
--- /dev/null
+++ b/ortools/glpk/CMakeLists.txt
@@ -0,0 +1,24 @@
+if(NOT USE_GLPK)
+  return()
+endif()
+
+file(GLOB _SRCS "*.h" "*.cc")
+
+set(NAME ${PROJECT_NAME}_glpk)
+
+# Will be merge in libortools.so
+#add_library(${NAME} STATIC ${_SRCS})
+add_library(${NAME} OBJECT ${_SRCS})
+set_target_properties(${NAME} PROPERTIES
+  CXX_STANDARD 17
+  CXX_STANDARD_REQUIRED ON
+  CXX_EXTENSIONS OFF
+  POSITION_INDEPENDENT_CODE ON
+  )
+target_include_directories(${NAME} PUBLIC
+  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}>
+  $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}>)
+target_link_libraries(${NAME} PRIVATE
+  absl::strings
+  $<$<BOOL:${USE_GLPK}>:GLPK::GLPK>)
+#add_library(${PROJECT_NAME}::glpk ALIAS ${NAME})
```

EDIT(mizux) (note: github task list need to be done in the first message)
* [x] Add CI workflow to test CMake GLPK build (i.e. `-DUSE_GLPK=ON`)
* [ ] Fix CMake GLPK support

**Comment by Mizux** [comment]
ok got it
https://github.com/google/or-tools/commit/42e0f3a2c1a277234a774c560172d98e940c13d9 enable it for the Bazel based build but nothing was done for the CMake based build -> break of the build.
