### ISSUE TITLE
mac m1 java Resource ortools-darwin-aarch64/ was not found in ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@311d617d

### ISSUE THREAD

**Issue by yupengj** [google/or-tools#3435]
**What version of OR-Tools and what language are you using?**
Version: 9.3.10497
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
MacBook Pro (13-inch, M1, 2020) 12.3.1 (21E258)

**What did you do?**

Loader.loadNativeLibraries()

**What did you expect to see**
Program executes correctly

**What did you see instead?**
```java
Exception in thread "main" java.lang.NullPointerException: Resource ortools-darwin-aarch64/ was not found in ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@311d617d
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at com.google.ortools.Loader.getNativeResourceURI(Loader.java:40)
	at com.google.ortools.Loader.loadNativeLibraries(Loader.java:107)
	at com.gant.common.ortools.MainLoader.main(MainLoader.java:7)
```
Make sure you include information that can help us debug (full error message, model Proto).

1. In order to reduce the interference code, simplified processing is done here
```java
package com.gant.common.ortools;

import com.google.ortools.Loader;

public class MainLoader {
    public static void main(String[] args) {
        Loader.loadNativeLibraries();
       ......
    }
}
```
2. I tried configuring `-Djna.prefix=darwin-x86-64` in jvm but got another error
```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/rt/zdvv0gzj11g3pp403lvlj5140000gn/T/ortools-java13295102952549420729/ortools-darwin-x86-64/libjniortools.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2622)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1835)
	at com.google.ortools.Loader.loadNativeLibraries(Loader.java:110)
	at com.gant.common.ortools.MainLoader.main(MainLoader.java:8)
```

**Anything else we should know about your project / environment**
Gradle

**Comment by lperron** [comment]
aarch64 is not supported for java on 9.3

**Comment by Mizux** [comment]
@yupengj  Please upgrade to v9.4.1874
ref: https://mvnrepository.com/artifact/com.google.ortools/ortools-java/9.4.1874
