### ISSUE TITLE
Test case python_python_prize_collecting_vrp_sat fails sometimes (timeout?)

### ISSUE THREAD

**Issue by StefanBruens** [google/or-tools#3461]
Version: v9.4

`ctest -j8 ...`
 
```
[  157s] 228/253 Test #210: python_python_prize_collecting_vrp_sat .....................................***Failed   19.31 sec
[  157s] Num nodes = 40
[  157s] Traceback (most recent call last):
[  157s]   File "/home/abuild/rpmbuild/BUILD/or-tools-9.4/examples/python/prize_collecting_vrp_sat.py", line 180, in <module>
[  157s]     main()
[  157s]   File "/home/abuild/rpmbuild/BUILD/or-tools-9.4/examples/python/prize_collecting_vrp_sat.py", line 175, in main
[  157s]     print_solution(solver, visited_nodes, used_arcs, num_nodes, num_vehicles)
[  157s]   File "/home/abuild/rpmbuild/BUILD/or-tools-9.4/examples/python/prize_collecting_vrp_sat.py", line 74, in print_solution
[  157s]     is_visited = sum([solver.BooleanValue(visited_nodes[v][node]) for v in range(num_vehicles)])
[  157s]   File "/home/abuild/rpmbuild/BUILD/or-tools-9.4/examples/python/prize_collecting_vrp_sat.py", line 74, in <listcomp>
[  157s]     is_visited = sum([solver.BooleanValue(visited_nodes[v][node]) for v in range(num_vehicles)])
[  157s]   File "/home/abuild/rpmbuild/BUILD/or-tools-9.4/build/python/venv/lib64/python3.10/site-packages/ortools/sat/python/cp_model.py", line 2270, in BooleanValue
[  157s]     return EvaluateBooleanExpression(literal, self.__solution)
[  157s]   File "/home/abuild/rpmbuild/BUILD/or-tools-9.4/build/python/venv/lib64/python3.10/site-packages/ortools/sat/python/cp_model.py", line 2160, in EvaluateBooleanExpression
[  157s]     return bool(solution.solution[index])
[  157s]   File "/usr/lib/python3.10/site-packages/google/protobuf/internal/containers.py", line 93, in __getitem__
[  157s]     return self._values[key]
[  157s] IndexError: list index out of range
[  157s] 
```

Apparently, passing "-jN" causes a massive oversubscription of the CPU for some test cases.

Changing the timeout to e.g. 25 seconds lets the TC pass reliably, for 5 it always fails.
https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/examples/python/prize_collecting_vrp_sat.py#L170

**Comment by lperron** [comment]
Thansk!
