### ISSUE TITLE
[Constraint Solver] CpModel proto exported after started search re-loads incorrectly

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#358]
I see the [commit](http://github.com/google/or-tools/commit/14b18ba11aab87422d8694d5da9619ad27977020) testing what I think is an oversimplified use of an exported proto model.

However, in production, in my use case in particular, export would occur during the search, or perhaps after breaking the search (i.e. during NextSolution, after the NewSearch/EndSearch boundaries).

Following which, just prior to running a new search, would re-load an existing proto if it existed. But which a search may been in the process of already running.

Furthermore, in addition to model, I think the proto should include stateful restoration; i.e. we should not be revisiting old ground, previously determined solutions.

Anything short of that is simply academic in my view and is not useful.

**Comment by mwpowellhtx** [comment]
The case being stated, I have also noticed that the re-loaded model breaks, is not restored in the same condition as when it was first arranged, after a search has begun running.

I will make PR that illustrates this fact.

**Comment by mwpowellhtx** [comment]
Moreover, I think that's a bug rooted in how IntVar's (or derivatives) are being treated generically as IntExpr. Although technically IntVar derives from IntExpr, the IntVar-iness should be preserved. Or BooleanVar, and so on.

**Comment by mwpowellhtx** [comment]
To be clear, the current example is academic in the sense that if all we're doing is exporting after arranging the model, constraints, etc, then running, this *doesn't add anything* to the equation. Why wouldn't we just pick up the *already-arranged* solver and run with *that*? Proto *doesn't add any value* to that picture. However, *correct restoration of a serialized solver state*, *does*.

**Comment by mwpowellhtx** [comment]
Pulled latest code from the repo. From what I can determine, definitely seems to be an improvement. However, it is still a bit inconsistent for my taste.

Here is output from *NUnit* testing. I will also be updating the *testcp.cs* accordingly with some more elaborated ``Check``(s).

```
  Expected string length 1010 but was 866. Strings differ at index 152.
  Expected: "..."Equal", "value", "expression", "variables" ], "expression..."
  But was:  "..."Equal", "value", "expression" ], "expressions": [ { "name..."
  --------------------------------------------^

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression)
   at Kingdom.Constraints.Sample.Fixturing.Tests.OrToolsTests.SimpleTestWithSearchMonitorsAndDecisionBuilder() in G:\Source\Kingdom Software\Kingdom.ConstraintSolvers\Working\src\Kingdom.Constraints.Sample.Fixturing.Tests\OrToolsTests.cs:line 493

First search...
x(0) + y(5) == 5
```

Given the assumptions we've discussed to this point, not surprisingly, what were once known as *variables* in the original version of the (exported) model, are then treated as *expressions* in the second version of the (loaded) model, as evidenced by the textual representation. IMO, IntVar-iness should be honored, or BooleanVar-iness, etc.

**Comment by mwpowellhtx** [comment]
Alright, so the issue turns out was the ``Solver`` left in a "searching" state. For whatever reason (I haven't dove into the code that deep, per se), ``EndSearch`` is required prior to any ``ExportModel``. But then I question the efficacy of wanting any *monitor(s)*, much less a ``DecisionBuilder``, per se. Anyway, this will need to be a puzzle for another day, for now.
