### ISSUE TITLE
Yet another "No module named 'ortools'" issue for python module

### ISSUE THREAD

**Issue by ogencoglu** [google/or-tools#3699]
I have gone through the closed issued with similar problems but they seem to mention visual studio redistributables. Yet, the [docs](https://developers.google.com/optimization/install) do not mention anything related to visual studio redistributable libraries at all.

![image](https://user-images.githubusercontent.com/8182738/223070090-8b5c4e7d-431c-4b7b-aaf6-92e171c4be55.png)

When I install with `pip` following the docs
`pip list` clearly shows it has been installed

`ortools                           9.5.2237`

Same with 
`python -m pip show ortools`

```
Name: ortools
Version: 9.5.2237
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google LLC
Author-email: or-tools@google.com
License: Apache 2.0
Location: /home/o/.local/lib/python3.9/site-packages
Requires: absl-py, numpy, protobuf
Required-by: 
```

But `import ortools` returns

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    from ortools.linear_solver import pywraplp
ModuleNotFoundError: No module named 'ortools.linear_solver'; 'ortools' is not a package
```

I am on ubuntu 20 with python 3.9.

Any help would be appreciated.
@lperron

**Comment by stradivari96** [comment]
`visual studio redistributable` is just for Windows I think.
are you sure you are on the same python env?

**Comment by Mizux** [comment]
Can you try this two command lines which should use the same python interpreter.
```sh
python -m pip show ortools
python -c "from ortools.linear_solver import pywraplp"
```
note: you may need to use `python3`

**Comment by ogencoglu** [comment]
`python3 -m pip show ortools` returns
```
Name: ortools
Version: 9.5.2237
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google LLC
Author-email: or-tools@google.com
License: Apache 2.0
Location: /home/o/.local/lib/python3.9/site-packages
Requires: absl-py, numpy, protobuf
Required-by:
```

as I mentioned in my original post.

`python3 -c "from ortools.linear_solver import pywraplp"` returns the error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/my_local_path/ortools.py", line 1, in <module>
    from ortools.linear_solver import pywraplp
ModuleNotFoundError: No module named 'ortools.linear_solver'; 'ortools' is not a package
```

with `-v`

I get:

```
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /usr/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc matches /usr/lib/python3.9/encodings/__init__.py
# code object from '/usr/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/codecs.cpython-39.pyc matches /usr/lib/python3.9/codecs.py
# code object from '/usr/lib/python3.9/__pycache__/codecs.cpython-39.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a63f3730>
# /usr/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc matches /usr/lib/python3.9/encodings/aliases.py
# code object from '/usr/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a638dcd0>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a63f3490>
# /usr/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc matches /usr/lib/python3.9/encodings/utf_8.py
# code object from '/usr/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a63f3970>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc matches /usr/lib/python3.9/encodings/latin_1.py
# code object from '/usr/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a638ddc0>
# /usr/lib/python3.9/__pycache__/io.cpython-39.pyc matches /usr/lib/python3.9/io.py
# code object from '/usr/lib/python3.9/__pycache__/io.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/abc.cpython-39.pyc matches /usr/lib/python3.9/abc.py
# code object from '/usr/lib/python3.9/__pycache__/abc.cpython-39.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a63a62b0>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a638dfa0>
# /usr/lib/python3.9/__pycache__/site.cpython-39.pyc matches /usr/lib/python3.9/site.py
# code object from '/usr/lib/python3.9/__pycache__/site.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/os.cpython-39.pyc matches /usr/lib/python3.9/os.py
# code object from '/usr/lib/python3.9/__pycache__/os.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/stat.cpython-39.pyc matches /usr/lib/python3.9/stat.py
# code object from '/usr/lib/python3.9/__pycache__/stat.cpython-39.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6343b20>
# /usr/lib/python3.9/__pycache__/_collections_abc.cpython-39.pyc matches /usr/lib/python3.9/_collections_abc.py
# code object from '/usr/lib/python3.9/__pycache__/_collections_abc.cpython-39.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6343bb0>
# /usr/lib/python3.9/__pycache__/posixpath.cpython-39.pyc matches /usr/lib/python3.9/posixpath.py
# code object from '/usr/lib/python3.9/__pycache__/posixpath.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/genericpath.cpython-39.pyc matches /usr/lib/python3.9/genericpath.py
# code object from '/usr/lib/python3.9/__pycache__/genericpath.cpython-39.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62d5220>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6343af0>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a63b9250>
# /usr/lib/python3.9/__pycache__/_sitebuiltins.cpython-39.pyc matches /usr/lib/python3.9/_sitebuiltins.py
# code object from '/usr/lib/python3.9/__pycache__/_sitebuiltins.cpython-39.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a63b9b20>
# /usr/lib/python3.9/__pycache__/_bootlocale.cpython-39.pyc matches /usr/lib/python3.9/_bootlocale.py
# code object from '/usr/lib/python3.9/__pycache__/_bootlocale.cpython-39.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62d56a0>
# /home/o/.local/lib/python3.9/site-packages/_distutils_hack/__pycache__/__init__.cpython-39.pyc matches /home/o/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py
# code object from '/home/o/.local/lib/python3.9/site-packages/_distutils_hack/__pycache__/__init__.cpython-39.pyc'
import '_distutils_hack' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62d5b20>
# /usr/lib/python3.9/__pycache__/types.cpython-39.pyc matches /usr/lib/python3.9/types.py
# code object from '/usr/lib/python3.9/__pycache__/types.cpython-39.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62feb80>
# /usr/lib/python3.9/importlib/__pycache__/__init__.cpython-39.pyc matches /usr/lib/python3.9/importlib/__init__.py
# code object from '/usr/lib/python3.9/importlib/__pycache__/__init__.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/warnings.cpython-39.pyc matches /usr/lib/python3.9/warnings.py
# code object from '/usr/lib/python3.9/__pycache__/warnings.cpython-39.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62fce80>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62fe220>
# /usr/lib/python3.9/importlib/__pycache__/util.cpython-39.pyc matches /usr/lib/python3.9/importlib/util.py
# code object from '/usr/lib/python3.9/importlib/__pycache__/util.cpython-39.pyc'
# /usr/lib/python3.9/importlib/__pycache__/abc.cpython-39.pyc matches /usr/lib/python3.9/importlib/abc.py
# code object from '/usr/lib/python3.9/importlib/__pycache__/abc.cpython-39.pyc'
# /usr/lib/python3.9/importlib/__pycache__/machinery.cpython-39.pyc matches /usr/lib/python3.9/importlib/machinery.py
# code object from '/usr/lib/python3.9/importlib/__pycache__/machinery.cpython-39.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62e43a0>
# /usr/lib/python3.9/__pycache__/typing.cpython-39.pyc matches /usr/lib/python3.9/typing.py
# code object from '/usr/lib/python3.9/__pycache__/typing.cpython-39.pyc'
# /usr/lib/python3.9/collections/__pycache__/__init__.cpython-39.pyc matches /usr/lib/python3.9/collections/__init__.py
# code object from '/usr/lib/python3.9/collections/__pycache__/__init__.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/heapq.cpython-39.pyc matches /usr/lib/python3.9/heapq.py
# code object from '/usr/lib/python3.9/__pycache__/heapq.cpython-39.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a625edf0>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.9/__pycache__/keyword.cpython-39.pyc matches /usr/lib/python3.9/keyword.py
# code object from '/usr/lib/python3.9/__pycache__/keyword.cpython-39.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62663a0>
# /usr/lib/python3.9/__pycache__/operator.cpython-39.pyc matches /usr/lib/python3.9/operator.py
# code object from '/usr/lib/python3.9/__pycache__/operator.cpython-39.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6266460>
# /usr/lib/python3.9/__pycache__/reprlib.cpython-39.pyc matches /usr/lib/python3.9/reprlib.py
# code object from '/usr/lib/python3.9/__pycache__/reprlib.cpython-39.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6266520>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62c42b0>
# /usr/lib/python3.9/collections/__pycache__/abc.cpython-39.pyc matches /usr/lib/python3.9/collections/abc.py
# code object from '/usr/lib/python3.9/collections/__pycache__/abc.cpython-39.pyc'
import 'collections.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62c4640>
# /usr/lib/python3.9/__pycache__/contextlib.cpython-39.pyc matches /usr/lib/python3.9/contextlib.py
# code object from '/usr/lib/python3.9/__pycache__/contextlib.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/functools.cpython-39.pyc matches /usr/lib/python3.9/functools.py
# code object from '/usr/lib/python3.9/__pycache__/functools.cpython-39.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6274e80>
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62c4850>
# /usr/lib/python3.9/__pycache__/re.cpython-39.pyc matches /usr/lib/python3.9/re.py
# code object from '/usr/lib/python3.9/__pycache__/re.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/enum.cpython-39.pyc matches /usr/lib/python3.9/enum.py
# code object from '/usr/lib/python3.9/__pycache__/enum.cpython-39.pyc'
import 'enum' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a621be20>
# /usr/lib/python3.9/__pycache__/sre_compile.cpython-39.pyc matches /usr/lib/python3.9/sre_compile.py
# code object from '/usr/lib/python3.9/__pycache__/sre_compile.cpython-39.pyc'
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.9/__pycache__/sre_parse.cpython-39.pyc matches /usr/lib/python3.9/sre_parse.py
# code object from '/usr/lib/python3.9/__pycache__/sre_parse.cpython-39.pyc'
# /usr/lib/python3.9/__pycache__/sre_constants.cpython-39.pyc matches /usr/lib/python3.9/sre_constants.py
# code object from '/usr/lib/python3.9/__pycache__/sre_constants.cpython-39.pyc'
import 'sre_constants' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6245910>
import 'sre_parse' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6235ee0>
import 'sre_compile' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a6235670>
# /usr/lib/python3.9/__pycache__/copyreg.cpython-39.pyc matches /usr/lib/python3.9/copyreg.py
# code object from '/usr/lib/python3.9/__pycache__/copyreg.cpython-39.pyc'
import 'copyreg' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a624f340>
import 're' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a625ec40>
import 'typing' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a63b90d0>
import 'importlib.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62fddc0>
import 'importlib.util' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62fe070>
# possible namespace for /home/o/.local/lib/python3.9/site-packages/google
# possible namespace for /home/o/.local/lib/python3.9/site-packages/mpl_toolkits
# possible namespace for /home/o/.local/lib/python3.9/site-packages/ruamel
# possible namespace for /home/o/.local/lib/python3.9/site-packages/zc
# /usr/lib/python3.9/__pycache__/sitecustomize.cpython-39.pyc matches /usr/lib/python3.9/sitecustomize.py
# code object from '/usr/lib/python3.9/__pycache__/sitecustomize.cpython-39.pyc'
import 'sitecustomize' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a62080a0>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x7f39a63a6a90>
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
# /home/my_local_path/__pycache__/ortools.cpython-39.pyc matches /home/my_local_path/ortools.py
# code object from '/home/my_local_path/__pycache__/ortools.cpython-39.pyc'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/my_local_path/ortools.py", line 1, in <module>
    from ortools.linear_solver import pywraplp
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ortools.linear_solver'; 'ortools' is not a package
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# destroy ortools
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _thread
# cleanup[2] removing _warnings
# cleanup[2] removing _weakref
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing posix
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing time
# cleanup[2] removing zipimport
# destroy zipimport
# cleanup[2] removing _codecs
# cleanup[2] removing codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing _abc
# cleanup[2] removing abc
# cleanup[2] removing io
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing _stat
# cleanup[2] removing stat
# cleanup[2] removing _collections_abc
# cleanup[2] removing genericpath
# cleanup[2] removing posixpath
# cleanup[2] removing os.path
# cleanup[2] removing os
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing _locale
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing _distutils_hack
# destroy _distutils_hack
# cleanup[2] removing types
# cleanup[2] removing importlib._bootstrap
# cleanup[2] removing importlib._bootstrap_external
# cleanup[2] removing warnings
# cleanup[2] removing importlib
# destroy importlib
# cleanup[2] removing importlib.machinery
# cleanup[2] removing _heapq
# cleanup[2] removing heapq
# cleanup[2] removing itertools
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing _operator
# cleanup[2] removing operator
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing collections
# cleanup[2] removing collections.abc
# cleanup[2] removing _functools
# cleanup[2] removing functools
# cleanup[2] removing contextlib
# cleanup[2] removing enum
# cleanup[2] removing _sre
# cleanup[2] removing sre_constants
# destroy sre_constants
# cleanup[2] removing sre_parse
# cleanup[2] removing sre_compile
# cleanup[2] removing copyreg
# cleanup[2] removing re
# cleanup[2] removing typing
# destroy typing
# cleanup[2] removing importlib.abc
# cleanup[2] removing importlib.util
# cleanup[2] removing google
# destroy google
# cleanup[2] removing mpl_toolkits
# destroy mpl_toolkits
# cleanup[2] removing ruamel
# destroy ruamel
# cleanup[2] removing zc
# destroy zc
# cleanup[2] removing sitecustomize
# destroy sitecustomize
# cleanup[2] removing site
# destroy site
# destroy time
# destroy _sitebuiltins
# destroy io
# destroy posixpath
# destroy _stat
# destroy genericpath
# destroy stat
# destroy os
# destroy importlib.util
# destroy importlib.abc
# destroy importlib.machinery
# destroy warnings
# destroy collections
# destroy contextlib
# destroy operator
# destroy re
# destroy types
# destroy heapq
# destroy collections.abc
# destroy _heapq
# destroy itertools
# destroy _operator
# destroy _collections
# destroy abc
# destroy _collections_abc
# destroy _abc
# destroy _functools
# destroy enum
# destroy sre_compile
# destroy functools
# destroy _locale
# destroy copyreg
# destroy sre_parse
# cleanup[3] wiping _sre
# cleanup[3] wiping importlib._bootstrap_external
# cleanup[3] wiping importlib._bootstrap
# destroy _frozen_importlib_external
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping _signal
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping posix
# cleanup[3] wiping marshal
# cleanup[3] wiping _io
# cleanup[3] wiping _weakref
# destroy _weakref
# cleanup[3] wiping _warnings
# cleanup[3] wiping _thread
# cleanup[3] wiping _imp
# destroy _imp
# cleanup[3] wiping _frozen_importlib
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy _sre
# destroy _signal
# destroy marshal
# destroy io
# destroy _warnings
# destroy _thread
# destroy posix
# destroy _frozen_importlib
# clear sys.audit hooks
```

**Comment by ogencoglu** [comment]
I was running the script from the command line btw,

**Comment by Mizux** [comment]
```
Type "help", "copyright", "credits" or "license" for more information.
# /home/my_local_path/__pycache__/ortools.cpython-39.pyc matches /home/my_local_path/ortools.py
# code object from '/home/my_local_path/__pycache__/ortools.cpython-39.pyc'
```
-> Can you verify, if you don't have an `ortools.py` in your current path which could fool python import....

**Comment by stradivari96** [comment]
Can I suggest removing the `--user` flag from the documentation?

**Comment by lperron** [comment]
No. Most systems ask for root privilege when --user is not specified.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 6 mars 2023 à 11:25, stradivari96 ***@***.***> a
écrit :

**Comment by ogencoglu** [comment]
Indeed my python script's name was `ortools.py` which messed up things I guess. It works now when I rename it. Apologies for the confusion and wasting your time.
