### ISSUE TITLE
MemoryError: SCIP: insufficient memory error!

### ISSUE THREAD

**Issue by smallsmallwood** [google/or-tools#3816]
ERROR:
Traceback (most recent call last):
  File "preallocation_api.py", line 185, in calculate
    main(day_pre=day_pre, day_now=day_now, task_id=task_id, task_type=task_type, mode=MODE,
  File "/opt/apps/app/../preallocation/order_distribute_main.py", line 103, in main
    od_algorithm.optimize()
  File "/opt/apps/app/../preallocation/order_distribute_algorithm_v4.py", line 530, in optimize
    self.model.optimize()
  File "src/pyscipopt/scip.pyx", line 3093, in pyscipopt.scip.Model.optimize
  File "src/pyscipopt/scip.pyx", line 234, in pyscipopt.scip.PY_SCIP_CALL
MemoryError: SCIP: insufficient memory error!

[prop_genvbounds.c:2454] ERROR: Error <-1> in function call
[prop.c:451] ERROR: Error <-1> in function call
[set.c:5286] ERROR: Error <-1> in function call
[scip_solve.c:709] ERROR: Error <-1> in function call
[scip_solve.c:3385] ERROR: Error <-1> in function call
[scip_prob.c:704] ERROR: Error <-1> in function call
[scip_general.c:325] ERROR: Error <-1> in function call
Traceback (most recent call last):
  File "src/pyscipopt/scip.pyx", line 234, in pyscipopt.scip.PY_SCIP_CALL
MemoryError: SCIP: insufficient memory error!
Exception ignored in: 'pyscipopt.scip.Model.__dealloc__'

linux 16c 80g
scip: 7.0.3
python:3.8.10
PySCIPOpt:3.2.1

**Comment by lperron** [comment]
reduce your model, decompose...

**Comment by lperron** [comment]
and use the SCIP forum.
