### ISSUE TITLE
No module named 'ortools.constraint_solver'

### ISSUE THREAD

**Issue by tmbenhura** [google/or-tools#3823]
**What version of OR-Tools and what language are you using?**
Version: 9.6.2534
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
constraint solver

**What operating system (Linux, Windows, ...) and version?**
Windows 11 Home 22H2

**What did you do?**
1.) I performed validation of my installation from the command prompt:
```bat
D:\> python --version
Python 3.8.3
D:\> python -c "import platform; print(platform.architecture()[0])"
64bit
D:\> python -m pip --version
pip 21.2.4 from C:\Python38\lib\site-packages\pip (python 3.8)
D:\>python -c "from ortools.constraint_solver import routing_enums_pb2"

D:\>python -c "from ortools.constraint_solver import pywrapcp"

D:>python tsp.py
Traceback (most recent call last):
  File "d:\tsp.py", line 1, in <module>
    from ortools.constraint_solver import routing_enums_pb2
  File "d:\tsp.py", line 1, in <module>
    from ortools.constraint_solver import routing_enums_pb2
ModuleNotFoundError: No module named 'ortools.constraint_solver'; 'ortools' is not a package
```

tsp.py below:
```py
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp


def create_data_model():
    """Stores the data for the problem."""
    data = {}
    # Locations in block units
    locations = \
            [(4, 4),  # depot
             (2, 0), (8, 0),  # locations to visit
             (0, 1), (1, 1),
             (5, 2), (7, 2),
             (3, 3), (6, 3),
             (5, 5), (8, 5),
             (1, 6), (2, 6),
             (3, 7), (6, 7),
             (0, 8), (7, 8),]
    # Convert locations in meters using a city block dimension of 114m x 80m.
    data['locations'] = [(l[0] * 114, l[1] * 80) for l in locations]
    data['num_vehicles'] = 1
    data['depot'] = 0
    return data


def create_distance_callback(data, manager):
    """Creates callback to return distance between points."""
    distances_ = {}
    index_manager_ = manager
    # precompute distance between location to have distance callback in O(1)
    for from_counter, from_node in enumerate(data['locations']):
        distances_[from_counter] = {}
        for to_counter, to_node in enumerate(data['locations']):
            if from_counter == to_counter:
                distances_[from_counter][to_counter] = 0
            else:
                distances_[from_counter][to_counter] = (
                    abs(from_node[0] - to_node[0]) +
                    abs(from_node[1] - to_node[1]))

    def distance_callback(from_index, to_index):
        """Returns the manhattan distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = index_manager_.IndexToNode(from_index)
        to_node = index_manager_.IndexToNode(to_index)
        return distances_[from_node][to_node]

    return distance_callback


def print_solution(manager, routing, assignment):
    """Prints assignment on console."""
    print('Objective: {}'.format(assignment.ObjectiveValue()))
    index = routing.Start(0)
    plan_output = 'Route for vehicle 0:\n'
    route_distance = 0
    while not routing.IsEnd(index):
        plan_output += ' {} ->'.format(manager.IndexToNode(index))
        previous_index = index
        index = assignment.Value(routing.NextVar(index))
        route_distance += routing.GetArcCostForVehicle(previous_index, index, 0)
    plan_output += ' {}\n'.format(manager.IndexToNode(index))
    plan_output += 'Distance of the route: {}m\n'.format(route_distance)
    print(plan_output)


def main():
    """Entry point of the program."""
    # Instantiate the data problem.
    data = create_data_model()

    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(len(data['locations']),
                                           data['num_vehicles'], data['depot'])

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)

    # Create and register a transit callback.
    distance_callback = create_distance_callback(data, manager)
    transit_callback_index = routing.RegisterTransitCallback(distance_callback)

    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

    # Solve the problem.
    assignment = routing.SolveWithParameters(search_parameters)

    # Print solution on console.
    if assignment:
        print_solution(manager, routing, assignment)


main()

```

**What did you expect to see**
Evaluation of the TSP example.

**What did you see instead?**
Error relating to missing package.

I also have, installed, VC++ 2015-2022 Redistributable 64 bit version 14.36.32532

**Comment by Mizux** [comment]
can you try a `python -m pip show ortools` to see if it is installed ?

**Comment by tmbenhura** [comment]
> can you try a `python -m pip show ortools` to see if it is installed ?

D:\>pip show ortools
Name: ortools
Version: 9.6.2534
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google LLC
Author-email: or-tools@google.com
License: Apache 2.0
Location: c:\users\xxxxxxx\appdata\roaming\python\python38\site-packages
Requires: numpy, scipy, protobuf, absl-py
Required-by:

**Comment by lperron** [comment]
Can you try running python with -v ?

https://stackoverflow.com/questions/7332299/trace-python-imports

**Comment by tmbenhura** [comment]
> Can you try running python with -v ?
> 
> https://stackoverflow.com/questions/7332299/trace-python-imports

It seems to have started working after a reinstall and restart.
