### ISSUE TITLE
9.7.2996 python package fails to declare dependency on pandas

### ISSUE THREAD

**Issue by dimbleby** [google/or-tools#3889]
**What version of OR-Tools and what language are you using?**
Version: 9.7
Language: python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 22

**What did you do?**
```
$ pip install ortools
Collecting ortools
  Downloading ortools-9.7.2996-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 9.9 MB/s eta 0:00:00
Collecting absl-py>=0.13
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 KB 13.6 MB/s eta 0:00:00
Collecting protobuf>=4.23.3
  Downloading protobuf-4.24.0-cp37-abi3-manylinux2014_x86_64.whl (311 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.6/311.6 KB 7.5 MB/s eta 0:00:00
Collecting numpy>=1.13.3
  Downloading numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 10.5 MB/s eta 0:00:00
Installing collected packages: protobuf, numpy, absl-py, ortools
Successfully installed absl-py-1.4.0 numpy-1.25.2 ortools-9.7.2996 protobuf-4.24.0

$ python -c 'from ortools.sat.python import cp_model'
```
**What did you expect to see**

No error

**What did you see instead?**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dch/.virtualenvs/foo/lib/python3.10/site-packages/ortools/sat/python/cp_model.py", line 68, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

No

**Comment by Mizux** [comment]
Good catch ^^;
https://github.com/google/or-tools/blob/ed8db9097cdbaa06b40384d3a86164744a606043/ortools/python/setup.py.in#L45-L49
