### ISSUE TITLE
bug:   macOs Loader.loadNativeLibraries error

### ISSUE THREAD

**Issue by earlylinzi** [google/or-tools#3930]
**What version of OR-Tools and what language are you using?**
    Version:          v9.3.10497
    Language:      Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
    CP-SAT

**What operating system (Linux, Windows, ...) and version?**
    macOS10.15.4

**What did you do?**
1. Use Idea to new a maven project.
2. import dependency to pom.xml like this:
![image](https://github.com/google/or-tools/assets/32222664/400f1ac1-244d-4446-a77f-61a3778d76da)
3. Test a MIP problem . The Code from https://developers.google.cn/optimization/mip/mip_example
4. Debug the main function.
5. See error like this:
Exception in thread "main" java.lang.NullPointerException: Resource ortools-darwin/ was not found in ClassLoader sun.misc.Launcher$AppClassLoader@18b4aac2
    at java.util.Objects.requireNonNull(Objects.java:228)
    at com.google.ortools.Loader.getNativeResourceURI(Loader.java:40)
    at com.google.ortools.Loader.loadNativeLibraries(Loader.java:107)
    at cn.xdf.api.pk.ortools.SimpleMipProgram.main(SimpleMipProgram.java:13)

**What did you expect to see**
I hope that my code can work.

**What did you see instead?**
See error like this:
Exception in thread "main" java.lang.NullPointerException: Resource ortools-darwin/ was not found in ClassLoader sun.misc.Launcher$AppClassLoader@18b4aac2
    at java.util.Objects.requireNonNull(Objects.java:228)
    at com.google.ortools.Loader.getNativeResourceURI(Loader.java:40)
    at com.google.ortools.Loader.loadNativeLibraries(Loader.java:107)
    at cn.xdf.api.pk.ortools.SimpleMipProgram.main(SimpleMipProgram.java:13)

**Anything else we should know about your project / environment?**
I located the line of code that reported the error:
![image](https://github.com/google/or-tools/assets/32222664/aea255bf-8437-4d9a-9e82-040bf35e17ba)
The "RESOURCE_PATH" come from "Platform.RESOURCE_PREFIX", and "Platform.RESOURCE_PREFIX" return "darwin"
![image](https://github.com/google/or-tools/assets/32222664/d1bfd528-9120-454b-b3e2-f9527993964a)
so "RESOURCE_PATH" = "ortools-darwin". But class loader cannot load by this name, becourse the name is "ortools-darwin-x86-64" like this :
![image](https://github.com/google/or-tools/assets/32222664/696d4653-7aea-4d6e-9ae3-24f702edfdd2)
I think that's why the error was reported.
So, I rewrite "RESOURCE_PATH"=ortools-darwin-x86-64 when running OS is macOs, the code can work.

Please fix this problem and look forward to your reply.

**Comment by earlylinzi** [comment]
> can you try with 9.7 ?

I try it. The v9.7 has the same problem

**Comment by earlylinzi** [comment]
> last version of jna-platform use a more consistent code base ref: [java-native-access/jna@ab2cb98](https://github.com/java-native-access/jna/commit/ab2cb98cb5b267d964d465ad95d8161808f18b97)

yea,  i update jna independency to v5.13.0 then my code can work.
![image](https://github.com/google/or-tools/assets/32222664/9eb6d45d-6d12-4eae-bf0e-8a2adf3a0cf0)

So, ortools-java should update jna version ,right?

**Comment by earlylinzi** [comment]
> https://mvnrepository.com/artifact/com.google.ortools/ortools-java/9.7.2996 that's the case using the last version.... note: before each release we try to be up to date with our dependencies.

OK， i see that.  i do not do it well when solve my project maven independency conflict.  
Updated to v9.7 my code can work well.
Think you for your Answers.
