### ISSUE TITLE
UnsatisfiedLinkError: com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.swig_module_init()V

### ISSUE THREAD

**Issue by rickbhardwaj** [google/or-tools#408]
Hey, 

Using the binary distributed for OSX, I was able to compile the ORTools jar. However, at runtime, I'm seeing this issue:

```
java.lang.UnsatisfiedLinkError: com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.swig_module_init()V
	at com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.swig_module_init(Native Method)
	at com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.<clinit>(operations_research_constraint_solverJNI.java:2330)
	at com.google.ortools.constraintsolver.RoutingModel.<clinit>(RoutingModel.java:652)
```

Here's the code I'm executing:
```
        RoutingModel routingModel = new RoutingModel(tour.getStops().size(),
                NUMBER_OF_ROUTES, NUMBER_OF_DEPOTS);
        routingModel.setArcCostEvaluatorOfAllVehicles(new ArcCostEvaluator(tour));
        RoutingSearchParameters searchParameters = RoutingSearchParameters.newBuilder()
                .mergeFrom(RoutingModel.defaultSearchParameters())
                .setFirstSolutionStrategy(FirstSolutionStrategy.Value.PATH_CHEAPEST_ARC)
                .build();
        Assignment solution = routingModel.solveWithParameters(searchParameters);
```

I'm trying to execute the code in IntelliJ, so I've added lib/ as a native library, the ORTools jar, and I've added -Djava.class.path=/lib as a runtime option as well.

Thanks for any help!

**Comment by rickbhardwaj** [comment]
Will reopen when I can reproduce issue.

**Comment by AdamKuzminski** [comment]
I have similar problem, did you find solution?

**Comment by rickbhardwaj** [comment]
Yes- it centers around library linking- when you call System.loadLibrary, Java can't discover the . If you're using an IDE like IntelliJ, follow the guides to link native libraries. If running from CLI, try setting -D=java.library.path to wherever your .so/.dll files are.
