### ISSUE TITLE
mathopt python error.

### ISSUE THREAD

**Issue by quantcn** [google/or-tools#4127]
I install ortools 9.9.3963 under windows 10 with python 3.8.8.
I write a test.py with only one line, that is: from ortools.math_opt.python import mathopt
I run it and gets the following error:
```
Traceback (most recent call last):
  File "e:/mypyoptimize/py-auto-roster-plant/test.py", line 1, in <module>
    from ortools.math_opt.python import mathopt
  File "E:\anaconda3\envs\optim\lib\site-packages\ortools\math_opt\python\mathopt.py", line 47, in <module>
    from ortools.math_opt.python.compute_infeasible_subsystem_result import (
  File "E:\anaconda3\envs\optim\lib\site-packages\ortools\math_opt\python\compute_infeasible_subsystem_result.py", line 60, in <module>
    class ModelSubset:
  File "E:\anaconda3\envs\optim\lib\site-packages\ortools\math_opt\python\compute_infeasible_subsystem_result.py", line 78, in ModelSubset
    variable_integrality: frozenset[model.Variable] = frozenset()
TypeError: 'type' object is not subscriptable
```
any idea?

**Comment by rma350** [comment]
We believe that the cause is from using frozenset as a type annotation, this is a Python 3.9 feature. It should be typing.FrozenSet instead if we want to maintain Python 3.8 compatibility. Until this is fixed, using Python 3.9+ should solve the problem if that is possible for you.
