### ISSUE TITLE
CP-SAT solver stopped working on Windows after updating to ortools 9.10

### ISSUE THREAD

**Issue by vaidzelevich** [google/or-tools#4225]
**What version of OR-Tools and what language are you using?**
Version: v9.10
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
The following simple script silently stops at the line `status = solver.solve(model)`. There is nothing in the console.

```python
from ortools.sat.python import cp_model


def simple_sat_program():
    model = cp_model.CpModel()

    num_vals = 3
    x = model.new_int_var(0, num_vals - 1, "x")
    y = model.new_int_var(0, num_vals - 1, "y")
    z = model.new_int_var(0, num_vals - 1, "z")

    model.add(x != y)
    
    solver = cp_model.CpSolver()
    solver.parameters.log_search_progress = True
    status = solver.solve(model)

    if status == cp_model.OPTIMAL or status == cp_model.FEASIBLE:
        print(f"x = {solver.value(x)}")
        print(f"y = {solver.value(y)}")
        print(f"z = {solver.value(z)}")
    else:
        print("No solution found.")


simple_sat_program()
```

**What did you expect to see**
Optimal values of `x`, `y`, `z`

**What did you see instead?**
Nothing.

**Comment by lperron** [comment]
strange, I just created a venv, installed ortools and ran the ortools/sat/samples without any problem.

**Comment by vaidzelevich** [comment]
Python 3.11.1

**Comment by lperron** [comment]
try another python version ? I used 3.12.3

**Comment by apavelm** [comment]
It looks like there are some breaking changes in CpSolver in 9.10 that doesn't work. But in python it doesn't reboot the server like in .NET #4224

**Comment by vaidzelevich** [comment]
Now everything is working fine. Updating the build tool for Visual Studio seems to help.

P.S. thanks for such a wonderful library.

**Comment by apavelm** [comment]
> P.S. thanks for such a wonderful library.

I agree, the library is really great!

**Comment by nhuet** [comment]
This is still not working for me on python 3.11 + windows + ortools 9.10. IMHO This should not be closed.

**Comment by nhuet** [comment]
And i have the same issue with python 3.12 also. Error shown:
```
Segmentation fault
```

**Comment by Mizux** [comment]
* #4227

**Comment by Shujee** [comment]
I'm facing this issue in .NET 9 on Windows 11 (`10.0.26100.6584`). Library version is `9.14.6206`. Program crashes with the following stack trace (doesn't throw any catchable exception; the app itself crashes instead. stack trace is from Event Viewer):

```
at Google.OrTools.Sat.operations_research_satPINVOKE.SolveWrapper_Solve(System.Runtime.InteropServices.HandleRef, Int32, Byte[])
at Google.OrTools.Sat.operations_research_satPINVOKE.SolveWrapper_Solve(System.Runtime.InteropServices.HandleRef, Int32, Byte[])
at Google.OrTools.Sat.SolveWrapper.Solve(Google.OrTools.Sat.CpModelProto)
at Google.OrTools.Sat.CpSolver.Solve(Google.OrTools.Sat.CpModel, Google.OrTools.Sat.SolutionCallback)
at ProSchool.Scheduler.CPScheduler+<>c__DisplayClass0_0.<Schedule>b__0()
at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

Simply downgrading to `9.9.3963` fixes the issue without any changes to my code.

The library itself is great though. It solves a complex scheduling problem very efficiently.

**Comment by lperron** [comment]
Try updating the c + + redistributable libraries.

Check the installed protobuf packages in all languages

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
