### ISSUE TITLE
CP-SAT model triggers bad hint in lns worker

### ISSUE THREAD

**Issue by lmores** [google/or-tools#4228]
**What version of OR-Tools and what language are you using?**
Version: 9.10.4067
Language: Java openjdk 21.0.2 2024-01-16 LTS

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 21.04 (64-bit, 5.11.0-49-generic)

**What did you do?**
I attempted to solve a CP model involving:

 - boolean vars
 - integer vars
 - interval vars
 - no overlap 2d constraint
 - greater or equal constraints
 - minimization function

Here is the model: [crash_issue.pb.txt](https://github.com/google/or-tools/files/15275153/crash_issue.pb.txt)

**What did you expect to see**
The program should exit normally.

**What did you see instead?**
```txt
$ mvn verify
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< ***OMISSIS*** >-----------------
[INFO] Building ***OMISSIS***
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ ***OMISSIS*** ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ ***OMISSIS*** ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ ***OMISSIS*** ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory ***OMISSIS***/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ ***OMISSIS*** ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ ***OMISSIS*** ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running ***OMISSIS***

Starting CP-SAT solver v9.10.4067
Parameters: max_time_in_seconds: 300 log_search_progress: true num_search_workers: 8 log_to_stdout: false log_to_response: true debug_crash_on_bad_hint: true

Initial optimization model '': (model_fingerprint: 0x5ba9df0c68ed4108)
#Variables: 66 (#ints: 2 in objective)
  - 7 Booleans in [0,1]
  - 6 in [0,12]
  - 2 in [0,14]
  - 4 in [0,16]
  - 1 in [0,17]
  - 1 in [0,18]
  - 1 in [0,19]
  - 5 in [0,21]
  - 2 in [0,23]
  - 14 in [0,24]
  - 4 in [0,25]
  - 1 in [0,26]
  - 1 in [0,27]
  - 1 in [0,28]
  - 14 in [0,33]
  - 1 in [14,33]
  - 1 in [26,33]
#kInterval: 30 (#fixed: 1)
#kLinear2: 14
#kLinear3: 14
#kNoOverlap2D: 1 (#rectangles: 15, #linear_areas: 1, #quadratic_areas: 14)

Starting presolve at 0.00s
The solution hint is incomplete: 52 out of 66 variables hinted.
  9.96e-05s  0.00e+00d  [DetectDominanceRelations] 
  8.93e-04s  0.00e+00d  [PresolveToFixPoint] #num_loops=3 #num_dual_strengthening=1 
  2.02e-05s  0.00e+00d  [ExtractEncodingFromLinear] 
[Symmetry] Graph for symmetry has 181 nodes and 205 arcs.
[Symmetry] Symmetry computation done. time: 0.000177786 dtime: 3.768e-05
[Symmetry] #generators: 3, average support size: 2.66667
[Symmetry] 4 orbits with sizes: 2,2,2,2
[Symmetry] Found orbitope of size 1 x 2
  5.93e-04s  1.32e-07d  [Probe] 
  2.34e-05s  0.00e+00d  [MaxClique] 
  4.25e-05s  0.00e+00d  [DetectDominanceRelations] 
  2.12e-04s  0.00e+00d  [PresolveToFixPoint] #num_loops=2 #num_dual_strengthening=1 
  1.72e-05s  0.00e+00d  [ProcessAtMostOneAndLinear] 
  5.13e-05s  0.00e+00d  [DetectDuplicateConstraints] 
  1.91e-05s  9.90e-08d  [DetectDominatedLinearConstraints] #relevant_constraints=16 
  1.20e-04s  0.00e+00d  [DetectDifferentVariables] #different=14 
  3.49e-06s  0.00e+00d  [ProcessSetPPC] 
  1.49e-05s  0.00e+00d  [FindAlmostIdenticalLinearConstraints] 
  5.77e-06s  0.00e+00d  [FindBigAtMostOneAndLinearOverlap] 
  9.56e-06s  6.40e-07d  [FindBigVerticalLinearOverlap] 
  2.14e-06s  0.00e+00d  [FindBigHorizontalLinearOverlap] 
  3.21e-06s  0.00e+00d  [MergeClauses] 
  3.60e-05s  0.00e+00d  [DetectDominanceRelations] 
  2.37e-04s  0.00e+00d  [PresolveToFixPoint] #num_loops=1 #num_dual_strengthening=1 
  2.45e-05s  0.00e+00d  [DetectDominanceRelations] 
  1.31e-04s  0.00e+00d  [PresolveToFixPoint] #num_loops=1 #num_dual_strengthening=1 
[Symmetry] Graph for symmetry has 183 nodes and 208 arcs.
[Symmetry] Symmetry computation done. time: 9.1646e-05 dtime: 3.544e-05
[Symmetry] #generators: 2, average support size: 3
[Symmetry] 3 orbits with sizes: 2,2,2
  2.81e-04s  1.32e-07d  [Probe] 
  5.30e-06s  0.00e+00d  [MaxClique] 
  3.24e-05s  0.00e+00d  [DetectDominanceRelations] 
  1.99e-04s  0.00e+00d  [PresolveToFixPoint] #num_loops=1 #num_dual_strengthening=1 
  2.12e-05s  0.00e+00d  [ProcessAtMostOneAndLinear] 
  3.16e-05s  0.00e+00d  [DetectDuplicateConstraints] 
  1.60e-05s  9.90e-08d  [DetectDominatedLinearConstraints] #relevant_constraints=16 
  7.86e-05s  0.00e+00d  [DetectDifferentVariables] #different=14 
  2.74e-06s  0.00e+00d  [ProcessSetPPC] 
  1.47e-05s  0.00e+00d  [FindAlmostIdenticalLinearConstraints] 
  4.36e-06s  0.00e+00d  [FindBigAtMostOneAndLinearOverlap] 
  7.91e-06s  6.40e-07d  [FindBigVerticalLinearOverlap] 
  1.63e-06s  0.00e+00d  [FindBigHorizontalLinearOverlap] 
  3.50e-06s  0.00e+00d  [MergeClauses] 
  2.93e-05s  0.00e+00d  [DetectDominanceRelations] 
  1.47e-04s  0.00e+00d  [PresolveToFixPoint] #num_loops=1 #num_dual_strengthening=1 
  1.75e-05s  0.00e+00d  [ExpandObjective] #entries=4 #tight_variables=2 #tight_constraints=1 

Presolve summary:
  - 21 affine relations were detected.
  - rule 'TODO dual: only one blocking constraint?' was applied 200 times.
  - rule 'TODO symmetry: add symmetry breaking inequalities?' was applied 1 time.
  - rule 'affine: new relation' was applied 21 times.
  - rule 'linear: always true' was applied 14 times.
  - rule 'linear: empty' was applied 7 times.
  - rule 'linear: fixed or dup variables' was applied 98 times.
  - rule 'linear: reduced variable domains' was applied 28 times.
  - rule 'linear: remapped using affine relations' was applied 21 times.
  - rule 'linear: simplified rhs' was applied 15 times.
  - rule 'presolve: 21 unused variables removed.' was applied 1 time.
  - rule 'presolve: iteration' was applied 2 times.
  - rule 'symmetry: added symmetry breaking inequality' was applied 1 time.

Presolved optimization model '': (model_fingerprint: 0x4983632c84155ecf)
#Variables: 24 (#ints: 2 in objective)
  - 6 in [0,12]
  - 2 in [0,14]
  - 4 in [0,16]
  - 1 in [0,17]
  - 1 in [0,18]
  - 1 in [0,19]
  - 2 in [0,21]
  - 1 in [0,23]
  - 2 in [0,25]
  - 1 in [0,27]
  - 1 in [0,28]
  - 1 in [14,33]
  - 1 in [26,33]
#kInterval: 30 (#fixed: 8)
#kLinear2: 15
#kLinear3: 1
#kNoOverlap2D: 1 (#rectangles: 15, #linear_areas: 1)

Preloading model.
#Bound   0.01s best:inf   next:[40,66]    initial_domain
The solution hint is complete, but it is infeasible! we will try to repair it.
[Symmetry] Graph for symmetry has 141 nodes and 208 arcs.
[Symmetry] Symmetry computation done. time: 6.5537e-05 dtime: 3.292e-05
[Symmetry] #generators: 2, average support size: 3
#Model   0.01s var:24/24 constraints:47/47

Starting search at 0.01s with 8 workers.
6 full problem subsolvers: [core, default_lp, max_lp, no_lp, quick_restart, reduced_costs]
1 first solution subsolver: [fj_short_default]
13 incomplete subsolvers: [feasibility_pump, graph_arc_lns, graph_cst_lns, graph_dec_lns, graph_var_lns, packing_precedences_lns, packing_rectangles_lns, packing_slice_lns, rins/rens, rnd_cst_lns, rnd_var_lns, scheduling_precedences_lns, violation_ls]
3 helper subsolvers: [neighborhood_helper, synchronization_agent, update_gap_integral]
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.735 s
[INFO] Finished at: 2024-05-10T14:31:35+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project ***OMISSIS***: There are test failures.
[ERROR] 
[ERROR] Please refer to ***OMISSIS***/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd ***OMISSIS*** && ***OMISSIS***/opt/jdk-21.0.2+13/bin/java -jar ***OMISSIS***/target/surefire/surefirebooter8820648775524585515.jar ***OMISSIS***/target/surefire 2024-05-10T14-31-34_158-jvmRun1 surefire13300156751279417494tmp surefire_05680107780706866962tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] ***OMISSIS***
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd ***OMISSIS*** && ***OMISSIS***/opt/jdk-21.0.2+13/bin/java -jar ***OMISSIS***/target/surefire/surefirebooter8820648775524585515.jar ***OMISSIS***/target/surefire 2024-05-10T14-31-34_158-jvmRun1 surefire13300156751279417494tmp surefire_05680107780706866962tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] ***OMISSIS***
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

Content of `target/surefire-reports/2024-05-10T14-31-34_158.dumpstream`:
```
# Created at 2024-05-10T14:31:35.142
QuickSolveWithHint() didn't find a feasible solution. The model name is ''. Status: +3.

# Created at 2024-05-10T14:31:35.142
*** Check failure stack trace: ***

# Created at 2024-05-10T14:31:35.236
Aborted (core dumped)
```

**Anything else we should know about your project / environment**
Nothing special

**Comment by lperron** [comment]
OK, remove the debug_crash_on_bad_hint:true

**Comment by lmores** [comment]
Solved, thank you!

**Comment by lmores** [comment]
When I closed the issue I thought that the issue was due to my hint values, I did not understand that the solver is crashing even if they are fine. I suppose the issue should stay open.

**Comment by lperron** [comment]
No, do not use this flag. This is a debug only flag.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
