### ISSUE TITLE
[Bazel] Building on Windows against MSVC is not working

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#4241]
Bazel based build is not working on windows due to too long path in protobuf

Related blocking issues:
* https://github.com/protocolbuffers/protobuf/issues/12947
   * https://github.com/bazelbuild/bazel/issues/19616

**Comment by Mizux** [comment]
on `main` seems blocked by rules_cc

```
Repository rule cc_autoconf defined at:
  D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/private/toolchain/cc_configure.bzl:109:30: in <toplevel>
ERROR: D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/private/toolchain/lib_cc_configure.bzl:112:9: An error occurred during the fetch of repository 'rules_cc++cc_configure_extension+local_config_cc':
   Traceback (most recent call last):
	File "D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/private/toolchain/cc_configure.bzl", line 89, column 36, in cc_autoconf_impl
		configure_windows_toolchain(repository_ctx)
	File "D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/private/toolchain/windows_cc_configure.bzl", line 881, column 35, in configure_windows_toolchain
		msvc_vars_x64 = _get_msvc_vars(repository_ctx, paths, "x64")
	File "D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/private/toolchain/windows_cc_configure.bzl", line 699, column 32, in _get_msvc_vars
		env = setup_vc_env_vars(repository_ctx, vc_path)
	File "D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/private/toolchain/windows_cc_configure.bzl", line 383, column 19, in setup_vc_env_vars
		envs = execute(repository_ctx, ["./get_env.bat"], environment = env).split(",")
	File "D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/private/toolchain/lib_cc_configure.bzl", line 206, column 32, in execute
		auto_configure_fail(
	File "D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/private/toolchain/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: non-zero exit code: 1, command ["./get_env.bat"], stderr: (The filename, directory name, or volume label syntax is incorrect.
)
ERROR: no such package '@@rules_cc++cc_configure_extension+local_config_cc//': 
Auto-Configuration Error: non-zero exit code: 1, command ["./get_env.bat"], stderr: (The filename, directory name, or volume label syntax is incorrect.
)
ERROR: D:/a/or-tools/or-tools/%userprofile%/appdata/local/temp/bazel/hrbwa772/external/rules_cc+/cc/BUILD:146:19: @@rules_cc+//cc:current_cc_toolchain depends on @@rules_cc++cc_configure_extension+local_config_cc//:cc-compiler-x64_windows in repository @@rules_cc++cc_configure_extension+local_config_cc which failed to fetch. no such package '@@rules_cc++cc_configure_extension+local_config_cc//': 
Auto-Configuration Error: non-zero exit code: 1, command ["./get_env.bat"], stderr: (The filename, directory name, or volume label syntax is incorrect.
)
```
ref: https://github.com/google/or-tools/actions/runs/19769378538/job/56649916539

**Comment by Mizux** [comment]
This may require bazel 9.0 at least for the pybind11_bazel part to have a working .pyd extension support.

note: pybind11_bazel BCR module is only tested against 9.x
ref: https://github.com/bazelbuild/bazel-central-registry/pull/8033/changes#diff-b9dc190b9d9324f67c83ce63a88d52fd2b30f58c8b2f28307a6f9b3164f605e8R28
