### ISSUE TITLE
Creating a WrappedConstraint with and/or operators on two WrappedConstraints results in a WrappedConstraint with a null operator.

### ISSUE THREAD

**Issue by joshua-jacobsen-flexrule** [google/or-tools#4346]
**What version of OR-Tools and what language are you using?**
Version: 9.10.4067
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Google.OrTools.ConstraintSolver
new Solver("CPSimple")

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
(here's a minimal function to demonstrate issue)
```cs
        public static string Main()
        {
            string output = "";
            Solver solver = new Solver("CPSimple");

            IntVar output1 = solver.MakeIntVar(0, 4, "output1");
            IntVar output2 = solver.MakeIntVar(0, 4, "output2");
            IntVar output5 = solver.MakeIntVar(5, 5, "output5");
            WrappedConstraint subject_operation = new WrappedConstraint((Constraint) (output5 >= output1));
            WrappedConstraint reference_operation = new WrappedConstraint((Constraint) (output5 >= output2));
            WrappedConstraint result = new WrappedConstraint(subject_operation && reference_operation);
            solver.Add(result);
            DecisionBuilder decisionBuilder = solver.MakePhase(new IntVar[] { output1, output2}, Solver.CHOOSE_FIRST_UNBOUND, Solver.ASSIGN_MIN_VALUE);
            solver.NewSearch(decisionBuilder);
            if (solver.NextSolution())
            {
                output = $"{output1.Value()}, {output2.Value()}";
            }
            return output;
        }
```
**What did you expect to see**
a boolean result from "solver.NextSolution() that I use to verify whether I have a solution or not.

**What did you see instead?**

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.Solver_NextSolution(System.Runtime.InteropServices.HandleRef)
--------------------------------
   at Google.OrTools.ConstraintSolver.Solver.NextSolution()
   at FlexRule_ORTools.SampleProblems.BugSample.Main()
   at Program.<Main>$(System.String[])
```
Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
After the "WrappedConstraint result = ...." line, the inspector shows:

◢ | result | {Google.OrTools.ConstraintSolver.WrappedConstraint} | Google.OrTools.ConstraintSolver.WrappedConstraint
  | ▶ Cst | null | Google.OrTools.ConstraintSolver.Constraint
  | Val | true | bool

I think the null here is what does it.

**Comment by joshua-jacobsen-flexrule** [comment]
Thanks!  Yeah, I wasn't necessarily convinced that && operators needed to be supported in this use case, and I ended up coding the same problem a different way, but it seemed that it should fail less catastrophically.
This worked fine:
WrappedConstraint result = new WrappedConstraint((Constraint) (subject_operation + reference_operation == 2));
