### ISSUE TITLE
Problem installing OR-Tools on windows as always

### ISSUE THREAD

**Issue by George35mk** [google/or-tools#512]
I have windows 10
and python 3.6.3

when i install the OR-tools with this commad:
```
pip install py3_ortools-6.4.4495-cp36-cp36m-win_amd64.whl
```

all install ok but:
I have this error: 

```
PS C:\Users\George35mk\Documents\GitHub\GEORGE35MK\products-offers-combinations> python or_tools.py
Traceback (most recent call last):
  File "C:\Users\George35mk\AppData\Local\Programs\Python\Python36\lib\site-packages\ortools\linear_solver\pywraplp.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\George35mk\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Δεν ήταν δυνατό να εντοπιστεί η καθορισμένη λειτ. μονάδα.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "or_tools.py", line 16, in <module>
    from ortools.linear_solver import pywraplp
  File "C:\Users\George35mk\AppData\Local\Programs\Python\Python36\lib\site-packages\ortools\linear_solver\pywraplp.py", line 17, in <module>
    _pywraplp = swig_import_helper()
  File "C:\Users\George35mk\AppData\Local\Programs\Python\Python36\lib\site-packages\ortools\linear_solver\pywraplp.py", line 16, in swig_import_helper
    return importlib.import_module('_pywraplp')
  File "C:\Users\George35mk\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywraplp'
PS C:\Users\George35mk\Documents\GitHub\GEORGE35MK\products-offers-combinations>
```

**Comment by lperron** [comment]
can you try pip3.6 install ortools?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-25 16:28 GMT+02:00 Georgios Chatoutsidis <notifications@github.com>:

**Comment by lperron** [comment]
Another possibilities is that you miss the C++ redistributable libraries
for visual studio 2017.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-25 16:34 GMT+02:00 Laurent Perron <lperron@google.com>:

**Comment by George35mk** [comment]
i have just installed visuall studio 2017 with c++ 14 build tools

**Comment by George35mk** [comment]
but i dont install with pip 3.6

**Comment by George35mk** [comment]
i type pip3.6 install ortools and now is dowloding something

**Comment by George35mk** [comment]
13.5mb file

**Comment by George35mk** [comment]
OMGGGGGGGGGGG WORKS BROOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by George35mk** [comment]
Thank sowwwww muchhhhhhhhhhhhhhhhhhh
