### ISSUE TITLE
Missing ortool.util in Python

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#558]
# Description
Currently on head (related to protobuf bump ?)
[linear_solver.proto:36](https://github.com/google/or-tools/blob/master/ortools/linear_solver/linear_solver.proto#L36) will generate `linear_solver_pb2.py`
with:
`from ortools.util import optional_boolean_pb2 as ortools_dot_util_dot_optional__boolean__pb2`

Thus if you try `examples/python/linear_programming.py` which has
`from ortools.linear_solver import linear_solver_pb2`, you.ll get:  
```sh
Traceback (most recent call last):
  File "../examples/python/linear_programming.py", line 16, in <module>
    from ortools.linear_solver import linear_solver_pb2
  File "/usr/local/google/home/corentinl/work/master/temp-python3.6/venv/lib/python3.6/site-packages/ortools-6.6.4761-py3.6-linux-x86_64.egg/ortools/linear_solver/linear_solver_pb2.py", line 17, in <module>
    from ortools.util import optional_boolean_pb2 as ortools_dot_util_dot_optional__boolean__pb2
ModuleNotFoundError: No module named 'ortools.util'
```

# Test protcol
Since `ortools/util` contains `__init.py__` you must use a pyenv to reproduce it
```sh
[...]
make clean_python UNIX_PYTHON_VER=3.6
make python UNIX_PYTHON_VER=3.6
make test_python UNIX_PYTHON_VER=3.6 # Could work since it use source dir and is not isolated !

make pypi_archive UNIX_PYTHON_VER=3.6
cd temp-python3.6 && python3.6 -m virtualenv -p python3.6 venv
# setup.py must be run from its directory
(cd ortools && ../venv/bin/python setup.py install)
venv/bin/python ../examples/python/linear_programming.py
```

Could be related to #527

**Comment by Mizux** [comment]
fix on master for Makefile here 238386a0f91c70a1842299f9a05b039c0de1d08b
