### ISSUE TITLE
Docker: Can't create ortools wheel package

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#616]
On manylinux:
```sh
creating build/bdist.linux-x86_64/wheel/ortools-6.7.4954.dist-info/WHEEL
creating '/root/src/temp-python2.7/ortools/dist/ortools-6.7.4954-cp27-cp27m-linux_x86_64.whl' and adding '.' to it
...
Repairing ortools-6.7.4954-cp27-cp27m-linux_x86_64.whl
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 11, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.6.4/lib/python3.6/site-packages/auditwheel/main.py", line 49, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.6.4/lib/python3.6/site-packages/auditwheel/main_repair.py", line 60, in execute
    wheel_abi = analyze_wheel_abi(args.WHEEL_FILE)
  File "/opt/_internal/cpython-3.6.4/lib/python3.6/site-packages/auditwheel/wheel_abi.py", line 73, in analyze_wheel_abi
    get_wheel_elfdata(wheel_fn)
  File "/opt/_internal/cpython-3.6.4/lib/python3.6/site-packages/auditwheel/wheel_abi.py", line 42, in get_wheel_elfdata
    so_path_split[-1])
RuntimeError: Invalid binary wheel, found shared library "_pywrapknapsack_solver.so" in purelib folder.
The wheel has to be platlib compliant in order to be repaired by auditwheel.
Makefile:140: recipe for target 'manylinux1-pypi' failed
make: *** [manylinux1-pypi] Error 1
```

I think, the issue come from setup.py now is shipped with its ".so" cf #551 so it is not a "pure lib" (has never been one BTW).
So setup.py should contains the same line than for the CMake based one cf https://github.com/google/or-tools/blob/master/cmake/python.cmake#L86 
```python
from setuptools import dist

class BinaryDistribution(dist.Distribution):
  def is_pure(self):
    return False
  def has_ext_modules(self):
    return True

setup(
...
distclass=BinaryDistribution,
```

On my way to test a patch

**Comment by Mizux** [comment]
Step to reproduce:

```sh
make python
cd temp-python2.7/ortools
python -m pip install wheel
python setup.py bdist_wheel

cd dist
python3.6 -m pip install auditwheel
python3.6 -m auditwheel show *.whl
```
Trace of the last line:
```sh
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/google/home/corentinl/.local/lib/python3.6/site-packages/auditwheel/__main__.py", line 5, in <module>
    sys.exit(main())
  File "/usr/local/google/home/corentinl/.local/lib/python3.6/site-packages/auditwheel/main.py", line 49, in main
    rval = args.func(args, p)
  File "/usr/local/google/home/corentinl/.local/lib/python3.6/site-packages/auditwheel/main_show.py", line 28, in execute
    winfo = analyze_wheel_abi(args.WHEEL_FILE)
  File "/usr/local/google/home/corentinl/.local/lib/python3.6/site-packages/auditwheel/wheel_abi.py", line 73, in analyze_wheel_abi
    get_wheel_elfdata(wheel_fn)
  File "/usr/local/google/home/corentinl/.local/lib/python3.6/site-packages/auditwheel/wheel_abi.py", line 42, in get_wheel_elfdata
    so_path_split[-1])
RuntimeError: Invalid binary wheel, found shared library "libortools.so" in purelib folder.
The wheel has to be platlib compliant in order to be repaired by auditwheel.
```

note: [auditwheel](https://pypi.python.org/pypi/auditwheel) is only available on Python 3

**Comment by Mizux** [comment]
Since merge of https://github.com/pypa/auditwheel/pull/35 auditwheel believe ortools whl package is a "pure lib" (doesn't use the [distclass Distribution informations](http://code.nabla.net/doc/setuptools/api/setuptools/dist/setuptools.dist.Distribution.html#setuptools.dist.Distribution.is_pure)).

So the best we can do, is disable
