### ISSUE TITLE
pyls_api.py work on Ubuntu 16.04 but crashes on 18.04

### ISSUE THREAD

**Issue by JohanJu** [google/or-tools#705]
```
python examples/python/pyls_api.py                                                                                                                                                    
Large Neighborhood Search
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0529 13:40:22.708248  4889 search.cc:241] Start search (memory used = 16.39 MB)
I0529 13:40:22.708333  4889 search.cc:241] Root node processed (time = 0 ms, constraints = 1, memory used = 16.39 MB)
I0529 13:40:22.708389  4889 search.cc:241] Solution #0 (objective value = 16, time = 0 ms, branches = 37, failures = 0, depth = 33, memory used = 16.39 MB)
Traceback (most recent call last):
  File "examples/python/pyls_api.py", line 121, in <module>
    main()
  File "examples/python/pyls_api.py", line 115, in main
    Solve(0)
  File "examples/python/pyls_api.py", line 110, in Solve
    solver.Solve(ls, [collector, obj, log])
  File "/home/jj/ws/ormini/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 331, in Solve
    return _pywrapcp.Solver_Solve(self, *args)
  File "/home/jj/ws/ormini/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 2740, in Start
    return _pywrapcp.IntVarLocalSearchOperatorTemplate_Start(self, assignment)
  File "/home/jj/ws/ormini/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 2740, in Start
    return _pywrapcp.IntVarLocalSearchOperatorTemplate_Start(self, assignment)
  File "/home/jj/ws/ormini/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 2740, in Start
    return _pywrapcp.IntVarLocalSearchOperatorTemplate_Start(self, assignment)
  [Previous line repeated 328 more times]
TypeError: in method 'IntVarLocalSearchOperatorTemplate_Start', argument 2 of type 'operations_research::Assignment const *'
F0529 13:40:22.794245  4889 constraint_solver.cc:1437] Check failed: 2 == searches_.size() (2 vs. 3) 
*** Check failure stack trace: ***
zsh: abort (core dumped)  python examples/python/pyls_api.py
```

I am on 2e4c5b3617c433ab5ccdad6f5f5f7ccaa82adda7 and my ubuntu 18.04 uses python 3.6.5 and gcc 7.3.0. I built with make third_party and make python

**Comment by billzhong** [comment]
@JohanJu you may want to add `UNIX_PYTHON_VER=3.6` when you make python.

**Comment by Mizux** [comment]
I can reproduce the error with `python 3` but not with `python 2`, currently investigating...

**Comment by lperron** [comment]
And I have pushed the fix.
At least on my mac with python3.6, it works fine.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
