### ISSUE TITLE
make install/release package

### ISSUE THREAD

**Issue by JohanJu** [google/or-tools#706]
Is it possible to make a release that is portable and small in size when building from source. It feels like there are absolute paths in the build as renaming the repository yield the following error:

```
Traceback (most recent call last):
  File "/home/jj/ws/ormini/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libortools.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nqueens.py", line 26, in <module>
    from ortools.constraint_solver import pywrapcp
  File "/home/jj/ws/ormini/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 17, in <module>
    _pywrapcp = swig_import_helper()
  File "/home/jj/ws/ormini/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrapcp')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrapcp'
```

**Comment by Mizux** [comment]
hi,

If you use master, you have `make pypi_archive` to create a wheel package (in tempdir/dist)
you can also install it using `make install_python` .
It is the recommended way than using the "buildir/src" directly....

ps: I should have patched all rpath so all links are relative on UNIX
