### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by MattiaZir** [google/or-tools#858]
Hello there,
I find the documentation to install the Java wrapper kinda confusing and lacking, but i "managed" to make it kinda work.

This is my procedure:

I made a directory in C:\or-tools and put the extracted binaries from the or-tools website inside it.

Then I put the jars in the libs folder in my gradle project and added the dependency like this:

`compile fileTree(dir: "libs", include: "*.jar")`
Then I added the following VM option:

`-Djava.library.path="C:\or-tools\libs"`
Now, when i run the program, it gives me the following error:

```
java.lang.UnsatisfiedLinkError: com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.swig_module_init()V
    at com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.swig_module_init(Native Method) ~[com.google.ortools.jar:na]
    at com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.<clinit>(operations_research_constraint_solverJNI.java:2346) ~[com.google.ortools.jar:na]
    at com.google.ortools.constraintsolver.RoutingModel.<clinit>(RoutingModel.java:652) ~[com.google.ortools.jar:na]
```

**Comment by MattiaZir** [comment]
Also, this is not at all a critique to the wonderful documentation, i just find it lacking and confusing because of my inexperience.

**Comment by Mizux** [comment]
Well the ortools.jar depends on other libs you must integrate everything in your solution.
We are providing a native dependent jar file.

Did you try to use the Makefile first to run java example to see if it works on your host ?
