### ISSUE TITLE
Trouble to build source to add SCIP solver in Nuget package with Version 6.9.5841

### ISSUE THREAD

**Issue by aJule** [google/or-tools#906]
Hi,
I am trying to rebuild the source to create a Or-Tools Nudget package with SCIP solver. I use windows 10 x64, and the x64 Native Tools Command Prompt for VS 2017.

* I start with the commands:
`C:\..\tools\make third_party`

* I add a  path for WINDOWS_SCIP_DIR in Makefile.local

* I execute the command
`C:\..\tools\make dotnet >`

* And when I test the result, with 
`C:\..\tools\make test_donet`
I have the following error about the Google.OrTools.runtime.win-x64.dll
```shell
[xUnit.net 00:00:02.1644022]     Google.OrTools.Tests.LinearProgramming.TestBinaryOperations [FAIL]
[xUnit.net 00:00:02.1871178]     Google.OrTools.Tests.LinearProgramming.TestVarOperator [FAIL]
[xUnit.net 00:00:02.1884312]     Google.OrTools.Tests.LinearProgramming.TestVarMultiplication [FAIL]
[xUnit.net 00:00:02.1893833]     Google.OrTools.Tests.LinearProgramming.TestSumArray [FAIL]
[xUnit.net 00:00:02.1902679]     Google.OrTools.Tests.LinearProgramming.TestInequalities [FAIL]
[xUnit.net 00:00:02.1912107]     Google.OrTools.Tests.LinearProgramming.TestVarAddition [FAIL]
[xUnit.net 00:00:02.1931569]     Google.OrTools.Tests.LinearProgramming.TestObjective [FAIL]
Non réussi(s) : Google.OrTools.Tests.LinearProgramming.TestBinaryOperations
```
Message d'erreur :
```shell
 System.TypeInitializationException : The type initializer for 'Google.OrTools.LinearSolver.Solver' threw an exception.
---- System.TypeInitializationException : The type initializer for 'Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE' threw an exception.
-------- System.TypeInitializationException : The type initializer for 'SWIGExceptionHelper' threw an exception.
------------ System.DllNotFoundException : Unable to load DLL 'Google.OrTools.runtime.win-x64.dll' or one of its dependencies: Le module spécifié est introuvable. (Exception from HRESULT: 0x8007007E)
Arborescence des appels de procédure :
   at Google.OrTools.Tests.LinearProgramming.TestBinaryOperations() in C:\..\ortools\dotnet\Google.OrTools.Tests\LinearProgramming.cs:line 94
----- Inner Stack Trace -----
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.Solver_CLP_LINEAR_PROGRAMMING_get()
   at Google.OrTools.LinearSolver.Solver..cctor()
----- Inner Stack Trace -----
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE..cctor()
----- Inner Stack Trace -----
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_linear_solver(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper..cctor()
...
```

When I unzip the nuget package Google.OrTools.runtime.win-x64.6.9.9999.nupkg, I have the following 
* Google.OrTools.runtime.win-x64.nuspec
* runtimes
   * win-x64
      * lib
        * netstandard2.0
          * Google.OrTools.dll
      * native
         * Google.OrTools.runtime.win-x64.dll

**Comment by lperron** [comment]
With the latest version, we rely on the SCIP windows installer, which produces a DLL.

So you will need to install this on your machine before installing the modified nuget package.
